// Generated by tools/build-cache.mjs; regenerate after all release edits.
self.HEXSURGE_RELEASE = {
  "version": "3d8eeaf1264a3aa7af9f16c07a1c3fa2a388faf68a5d27ffcb4cc420c6fd2d5a",
  "assets": [
    {
      "path": "app.js",
      "hash": "8429aff9e1941a099ff3f6a0e0958c15953161686deb386f5a8a81944d51727a"
    },
    {
      "path": "assets/branding/logo.svg",
      "hash": "7ecb241edb6fb68c7916d14a8f8babb623e1b68ecd3f4e1576cf3aaa11b4aecd"
    },
    {
      "path": "assets/branding/mark.svg",
      "hash": "05b65eaa34f034d0d1f90b50645336aac3d7d3644da8a00da13b913e833861fc"
    },
    {
      "path": "assets/css/base.css",
      "hash": "5229faf0e42b6068c18eb00d55519d2b8a5607880227eb40b9b9552532f25eda"
    },
    {
      "path": "assets/css/battle.css",
      "hash": "141a89df1a8e96b5c96f556d2d4eddc843ddf651c742f2dd53887720620e3ce7"
    },
    {
      "path": "assets/css/codex.css",
      "hash": "5906441c054803857b057a346a2ae0c27591875ca68c3179f2ca759b2bc42812"
    },
    {
      "path": "assets/css/menu.css",
      "hash": "236e36f85b05e0f2a150b07f3bf32ca2f7e7b9776d8b01554593513e43ec1480"
    },
    {
      "path": "assets/css/results.css",
      "hash": "8eb5da63b762c397751a4fff8d6bb4166529a2934eb692358fd1308c7ec639a7"
    },
    {
      "path": "assets/css/settings.css",
      "hash": "040aa782eaeee2f896e12bcfeb2dd49e0bbb9b75e480bcb4dede6b55da84055f"
    },
    {
      "path": "assets/icons/apple-touch-icon.png",
      "hash": "98db9692f570c3a2593d6a32259de732c7d1133ff929600f150a245f6cc870c3"
    },
    {
      "path": "assets/icons/icon-192.png",
      "hash": "ad0a53a21b9ec2574caee4b08774b25764f91ca061468444b08c1b3deb253d43"
    },
    {
      "path": "assets/icons/icon-512.png",
      "hash": "40cb3c7b2f04c71991ac6be6a697324cf0520b79b45b8793769d23af758e3bf7"
    },
    {
      "path": "assets/icons/icon-maskable-512.png",
      "hash": "05a612ff4fb0f53085e4fc474c4cd4ab7f147ad99306569614e20ff622c45cde"
    },
    {
      "path": "assets/icons/icon.svg",
      "hash": "0adf44b5e31b37ab27382cc75d6a9417786eb27510ccbf6a62ba9831304917c2"
    },
    {
      "path": "assets/illustrations/bosses/fallen_archmage.svg",
      "hash": "b99038d709168d262c953812769aae47331acef573bba843b2b00c690ab27e1e"
    },
    {
      "path": "assets/illustrations/bosses/ignarok.svg",
      "hash": "80b5cb29044027419be355c788905a0d5c2097061e1b3e6136b8b716f93b8454"
    },
    {
      "path": "assets/illustrations/bosses/nullgaze.svg",
      "hash": "e43205eb32b6a344d0730ced5f41af5f7e01bd1da24eed24ba335522c50288f6"
    },
    {
      "path": "assets/illustrations/bosses/rimewing.svg",
      "hash": "6d17aaf57bb822aa8a35b30b2f7220250320279d21cbf1cf7905c07768033df3"
    },
    {
      "path": "assets/illustrations/bosses/rotwood_king.svg",
      "hash": "4f025e0004a4202e5e46d75885dd5d89e70dddf555f04597648793f4d203180c"
    },
    {
      "path": "assets/illustrations/elements/arcane.svg",
      "hash": "b99706f25f1b686148a70605003438ca9fc46292d34d11b06ec5c44a045ac50e"
    },
    {
      "path": "assets/illustrations/elements/fire.svg",
      "hash": "13ab753d425a62705080c66526da4d0ef1efa0d5fd430d29f0be0e9ab74577bc"
    },
    {
      "path": "assets/illustrations/elements/ice.svg",
      "hash": "cee1b8ca591064b78c15421c81a0be4ab33d48cdf07d08e2dd97b75b4e688ea8"
    },
    {
      "path": "assets/illustrations/elements/nature.svg",
      "hash": "1630b65308e0ded46994e815d26b5a50f6d60115840ec77dc8024c7c2516bca0"
    },
    {
      "path": "assets/illustrations/elements/thunder.svg",
      "hash": "efbf198b43c5ecf89a43dd4bb51c1904636b5416d0bad98701a566face6b6fc8"
    },
    {
      "path": "assets/illustrations/elements/void.svg",
      "hash": "515258ab828652c3fc27d90e8e2d61d4ff6c57235dfd9c3e966a5753bcf8fd6c"
    },
    {
      "path": "assets/illustrations/enemies/arc_gunner.svg",
      "hash": "d5efe9824a105c60473edc0aa97c99a4250f98074506d40d08afee36dfe6b749"
    },
    {
      "path": "assets/illustrations/enemies/banner_knight.svg",
      "hash": "dc65e1b523160f95e65d512220176d2c31d6e81769ebe71d4746cc844b7a3c3c"
    },
    {
      "path": "assets/illustrations/enemies/bomb_imp.svg",
      "hash": "77fb193d481b5f7a6193d6b232cf8a1454b2a02182762db98b5448c49cafadc8"
    },
    {
      "path": "assets/illustrations/enemies/brood_mother.svg",
      "hash": "8214fd95798442a95443930786f8dc9c85bf769b7a9c5ee8510c8d145aed83b2"
    },
    {
      "path": "assets/illustrations/enemies/brood_spawn.svg",
      "hash": "1b3775c328f10a06ff93cf4d96c5438c9a1c353e5fe9495297dfdc0784611d0a"
    },
    {
      "path": "assets/illustrations/enemies/colossus.svg",
      "hash": "98eb19962b2b3d397cbc52efc151335d0c7ea394adc25d23a31c5e8e59c08c5e"
    },
    {
      "path": "assets/illustrations/enemies/cult_archer.svg",
      "hash": "7e4081759e5e17a6869fe68e00be6f28cc677aa71e49967106740c305f875059"
    },
    {
      "path": "assets/illustrations/enemies/fangwolf.svg",
      "hash": "e244e5f096c424bdd710f3c099cb64e4f59c33f53f2148e241fb3d4479386dda"
    },
    {
      "path": "assets/illustrations/enemies/ghoul.svg",
      "hash": "05d6e0dc9a874992728bedc1008b02945f21700b58965362bdee2caf27273887"
    },
    {
      "path": "assets/illustrations/enemies/gloom_bat.svg",
      "hash": "a84c58a6a84db07ee85a551a7b59186d329208c67c3458cde5f559b5cd7f48ef"
    },
    {
      "path": "assets/illustrations/enemies/harpy.svg",
      "hash": "821c8c2f7b02abf75bac05e95dac3969bc297c4845cbca04c6c01cc6eacd00eb"
    },
    {
      "path": "assets/illustrations/enemies/hex_caster.svg",
      "hash": "16b3a02efef3f5d278ffa3bbd3a767cb8ed9f75b3ff6e0e4bccbd607bf80e204"
    },
    {
      "path": "assets/illustrations/enemies/hive_queen.svg",
      "hash": "2eed0fa7266f437693b8344300485980e16a084de43090fe57a6e80ac4af5302"
    },
    {
      "path": "assets/illustrations/enemies/imp.svg",
      "hash": "34d70c3ac93b56e213e30a01c99d2bbe29b949a3fd95398a0a46002cc619d844"
    },
    {
      "path": "assets/illustrations/enemies/iron_ogre.svg",
      "hash": "816dbd72835bf76cf5c55d941f0428d5d43c3eeb23de91fae1ed6212dfe25b04"
    },
    {
      "path": "assets/illustrations/enemies/life_weaver.svg",
      "hash": "e81cb13380cb1b0c499d2ab6ce5ba8c46ff0f7f9caaa2af09d242f6c663f126a"
    },
    {
      "path": "assets/illustrations/enemies/magma_bomber.svg",
      "hash": "eb60716b880250c51241e7b65c9d2b261657833d9d5f09c62762e944d4bfccb5"
    },
    {
      "path": "assets/illustrations/enemies/mender.svg",
      "hash": "6bcbe747822303ccb654d8437dfcfb87144455a0d5a52cb75d2d6ae3214bc52f"
    },
    {
      "path": "assets/illustrations/enemies/necromancer.svg",
      "hash": "957f537732a46667f09df84d319b76b61c5117b4c018e607f53659e4e232cb70"
    },
    {
      "path": "assets/illustrations/enemies/revenant.svg",
      "hash": "737cb85f85b5a4c27c8791cf5f3db43bc9534e4f37c00efa8cb32d36c41ddd9b"
    },
    {
      "path": "assets/illustrations/enemies/shade_stalker.svg",
      "hash": "04f68d531ce59afceb7b8c9e11f1536f41600e27c849d2d7012e8ceceba92981"
    },
    {
      "path": "assets/illustrations/enemies/slime.svg",
      "hash": "833f623b57f585d962581b9bcd8d090c951a622ae37f8ac6cfa1d45b7f03b9ec"
    },
    {
      "path": "assets/illustrations/enemies/slime_bit.svg",
      "hash": "d6857e02b390bc17d1e217bd6f0802361afcd84bb5cdc6ef41ccd8f52a20bbb1"
    },
    {
      "path": "assets/illustrations/enemies/stone_brute.svg",
      "hash": "1593d9c4a34462e4412d6aae0e8eda0dfbd77a30d68d0f3beb6a004060e67615"
    },
    {
      "path": "assets/illustrations/enemies/war_drummer.svg",
      "hash": "e79abe14ed5cc55eb01f51bb3a0edc5a392754244c77f2a75679a3c49f7b4dd4"
    },
    {
      "path": "assets/illustrations/enemies/wraith.svg",
      "hash": "5a551d5a4c1247a99955dbf50be1971ed417a5370cfe492cb733103b53b530aa"
    },
    {
      "path": "assets/illustrations/mages/arcanis.svg",
      "hash": "47e885e402f5ea2122c40fb253d0f1cd8da99e8f424c2fbe40e960afb5936a09"
    },
    {
      "path": "assets/illustrations/mages/glacia.svg",
      "hash": "4e70c10e2d7fb1d26d5e8102aba2a026e7f152d9ee98ee96edc5d77c8519be04"
    },
    {
      "path": "assets/illustrations/mages/ignis.svg",
      "hash": "757df3675daf01c96b6cf1bafd763dcbc5ea122b1882d47dc99ee1e2f6b135c7"
    },
    {
      "path": "assets/illustrations/mages/nox.svg",
      "hash": "f93012da0c2dea9f3c8edee364b3101ec748d7e35a957914d0e03973a88d3e9f"
    },
    {
      "path": "assets/illustrations/mages/sylva.svg",
      "hash": "7453ce53e33d7a13036cdc015dc23710b9654f58be4cf05e5f217321664caaea"
    },
    {
      "path": "assets/illustrations/mages/voltra.svg",
      "hash": "1615acfda6cc7bc4ca1e8dd101970e1d1435ded9be4301b0d15fb4ef1a39aa1a"
    },
    {
      "path": "assets/illustrations/maps/abyss.svg",
      "hash": "44553daeb3a343cdb84ef8708cf3cf1a57e0e6d5a89180584d6702f85f691ec8"
    },
    {
      "path": "assets/illustrations/maps/academy.svg",
      "hash": "2fa09745f0e351675cc1d475c938157f11c13b21a7476963ca3df9c720e7146b"
    },
    {
      "path": "assets/illustrations/maps/forest.svg",
      "hash": "dffe852916a5558fa3a0d743c408f68013e021bc78fe89b07608b6cd5bc71b1f"
    },
    {
      "path": "assets/illustrations/maps/tundra.svg",
      "hash": "c3873708344de70538e20a4ee88c443b18cfd8f38f5dd3c8432d114422ed03c3"
    },
    {
      "path": "assets/illustrations/maps/void.svg",
      "hash": "be450d4c8f79e579648b4c039f5c3aeb082c325e09d2de4c9b0818e807b886f1"
    },
    {
      "path": "assets/illustrations/passives/clover.svg",
      "hash": "0c5bfaae00d39df75a1019a1cf682475b754a8cca460a985f5ea4c20fc93b52f"
    },
    {
      "path": "assets/illustrations/passives/echo_gem.svg",
      "hash": "4970f1d19fb50600c64a981eab6711e2eeb879e800acced7911316c5677f7c10"
    },
    {
      "path": "assets/illustrations/passives/hourglass.svg",
      "hash": "b758e6fa9a36e3ee630165faa15ff9ea42f0c2e33de90f0b4c7ec60cc04e7d27"
    },
    {
      "path": "assets/illustrations/passives/magnet_charm.svg",
      "hash": "ec3fc6c2e5c993f67b8a560b1d9e57c4326c47d0731b78157bffa5081df0fbe4"
    },
    {
      "path": "assets/illustrations/passives/power_sigil.svg",
      "hash": "2ed7799b8e15849c74e45ee185a3e42e4de307c5c545e720d9241fd4ed9e1210"
    },
    {
      "path": "assets/illustrations/passives/scholar_lens.svg",
      "hash": "a0510507832902b6ee0006be563870d503ca15adf8556e97234b401ca7e7f2e5"
    },
    {
      "path": "assets/illustrations/passives/tome_haste.svg",
      "hash": "02a3c558d0c4a0f2ce4bddf3ce9b1c5dffb8a3b7bc962418bb18ef8724e49a8d"
    },
    {
      "path": "assets/illustrations/passives/twin_crest.svg",
      "hash": "45f286e55ada66bb38753ad44cf8a1cb5ae73d2c7f393e0e9f0716f88c727a23"
    },
    {
      "path": "assets/illustrations/passives/vitality.svg",
      "hash": "afa068790003dba11eccf734ed4ccc596cc051a0be223ef77350a2be0614c1a2"
    },
    {
      "path": "assets/illustrations/passives/ward_amulet.svg",
      "hash": "db2f2279f3333e57ec2d63860a03d455e3dc857fe700d90af862f373708203ba"
    },
    {
      "path": "assets/illustrations/passives/wide_sigil.svg",
      "hash": "f75e678f3e1419158fa8670d51f52928847d29d20fa76f0ebc94766e32d37618"
    },
    {
      "path": "assets/illustrations/passives/wind_boots.svg",
      "hash": "0a47b3478d42563c14c9b2a830abc60e1829387ed18bcf92b7c6905be5ecc949"
    },
    {
      "path": "assets/illustrations/spells/absolute_zero.svg",
      "hash": "ac529165c40b9031aab1c5ba76aeb1304ed7569183c7a5844227bfee65f39854"
    },
    {
      "path": "assets/illustrations/spells/aegis_of_mana.svg",
      "hash": "4e4daeae0feabfea2112e78c2b6f3e94f33225297bb768494b1357c5a0fea292"
    },
    {
      "path": "assets/illustrations/spells/arcane_barrage.svg",
      "hash": "b05c198e88aae49faf056b3866aa7b95075d947f4aaa127b6fae236a577d13c6"
    },
    {
      "path": "assets/illustrations/spells/arcane_missiles.svg",
      "hash": "e2184e600355e8e0f43cfb08401a59f53883a08864512afec0c69f74d2c1860e"
    },
    {
      "path": "assets/illustrations/spells/arcane_orbs.svg",
      "hash": "1da3307279ce91682ad5b3df0b47b210274860851737b686ad0687a4f9402145"
    },
    {
      "path": "assets/illustrations/spells/black_hole.svg",
      "hash": "4bb80c7e4e601b6e6d63d821c421ee4be1cde39090264e848db6a34fe9225fd8"
    },
    {
      "path": "assets/illustrations/spells/blade_tempest.svg",
      "hash": "8a5d0b45e743f47c089b3de43539ec524210d3613deb48c04e14fadc37f563b8"
    },
    {
      "path": "assets/illustrations/spells/celestial_orrery.svg",
      "hash": "7bb0c91784dde35764c1f905245c01a10950e1a1219dbdba857e9dd93b101933"
    },
    {
      "path": "assets/illustrations/spells/chain_lightning.svg",
      "hash": "12f5255d5e4ed65cba952434dce5adcbf0285e7871b393ffbd26ccbfa2b6a882"
    },
    {
      "path": "assets/illustrations/spells/ember_field.svg",
      "hash": "bd0729a6536bd344708dfdb7fb2e441e00ba7096dc15f6bf98bfc5894586f3d2"
    },
    {
      "path": "assets/illustrations/spells/entropy_aura.svg",
      "hash": "dffacca88afd6e40516c3650e849f9d01122ef70535971835e5fd176980eca02"
    },
    {
      "path": "assets/illustrations/spells/fenrir_pack.svg",
      "hash": "f5f5183ad2bac6aa78d0b0f3be832059a0d76425ce79a32acdbd342d5c640106"
    },
    {
      "path": "assets/illustrations/spells/fireball.svg",
      "hash": "23781cea1e6cdc98cd441ac4b3def5e7b6a737e8e1b8592bc25e7f35688fb65d"
    },
    {
      "path": "assets/illustrations/spells/flame_wheel.svg",
      "hash": "ffdbc8541fb6accf8d9456d04d9238975c45cb3c3d5c2aac0026c73ae0bd5f74"
    },
    {
      "path": "assets/illustrations/spells/frost_nova.svg",
      "hash": "d1ed3938cb04aab217c3ae885f89ebcc0f85ff8fa4dd4d76050b4a48d8813180"
    },
    {
      "path": "assets/illustrations/spells/frozen_bastion.svg",
      "hash": "5b227ac5ac0940c5ed9a6e30a84772bd63d941c67d04608a4e0f3841bf0124aa"
    },
    {
      "path": "assets/illustrations/spells/glacial_ward.svg",
      "hash": "030229ba0d681e76a5a160446cb90007626b2d2af68c4b5d8cdd1ad27f7d6ded"
    },
    {
      "path": "assets/illustrations/spells/heat_death.svg",
      "hash": "ea5907aa5557d036189406dc8ac0c519b160a2da578873adace452891acf7223"
    },
    {
      "path": "assets/illustrations/spells/ice_lance.svg",
      "hash": "f876625086c755db08c5ed44e52ae456345259e5179b4bc815d13d0ae697c5ef"
    },
    {
      "path": "assets/illustrations/spells/mana_barrier.svg",
      "hash": "43feecdd6797f8b0f14c2b8eb239c326ee43eaf6ebe36b1906bf400ac132677a"
    },
    {
      "path": "assets/illustrations/spells/meteor_rain.svg",
      "hash": "1848668a0b8b4fdfd938d2e23204e75c863f0a8755597ea1aea53ca870b01ba0"
    },
    {
      "path": "assets/illustrations/spells/phoenix_ring.svg",
      "hash": "0b161558f1ff0715ac156a0f45b21abf838052afc747d95b93246ef20e1272e8"
    },
    {
      "path": "assets/illustrations/spells/polar_storm.svg",
      "hash": "92ad00a4711ff40b25f9b80f480eec227332f135f6a227117249dbfcc3d83100"
    },
    {
      "path": "assets/illustrations/spells/razor_leaf.svg",
      "hash": "2983c12ec7b9e2d330e13a06562b91344303121963fea78410e2bac91eb326a8"
    },
    {
      "path": "assets/illustrations/spells/shadow_familiar.svg",
      "hash": "afd99be9274bf918da04478225f755403dfda4c40cd1ef4200d031d9b15941ca"
    },
    {
      "path": "assets/illustrations/spells/shadow_legion.svg",
      "hash": "874965c1bbe47bb115aed5c8065cb4a1aeb3f41b373049a0d2f6b8a331733dbb"
    },
    {
      "path": "assets/illustrations/spells/sky_judgement.svg",
      "hash": "5f76797a22df4714619680bccbfbd61057047ea50d9b3dd5fec988b28407479b"
    },
    {
      "path": "assets/illustrations/spells/spirit_wolf.svg",
      "hash": "5597f4e907641c18e7ad19999f1d620acda78e19d13bfce7c0874cfa0602fc74"
    },
    {
      "path": "assets/illustrations/spells/storm_roc.svg",
      "hash": "16f0b6d237ecc8cce476b8ff982105d4c3e48d5da2396743d1231b2e6f5d17e8"
    },
    {
      "path": "assets/illustrations/spells/storm_wrath.svg",
      "hash": "6fdb0ae768f2f9a221988711198f654604643d39fb9f64970a5f1dda945a97f1"
    },
    {
      "path": "assets/illustrations/spells/thorn_field.svg",
      "hash": "bccb4fde487870c00d6d2a90839577bc8e721f609050bedb79d225c569470fc8"
    },
    {
      "path": "assets/illustrations/spells/thunder_hawk.svg",
      "hash": "55e6311a4f12a6fb7cc9467d5c5b3cc5f382df8f91ad5bb2eabc554afcae36c0"
    },
    {
      "path": "assets/illustrations/spells/thunderstrike.svg",
      "hash": "13022b897328243743e2edfbeab854cd29ed2c91d1f96c3ec04da5155ee8814d"
    },
    {
      "path": "assets/illustrations/spells/void_rift.svg",
      "hash": "4f995dcd8df2afa8a339ab70a74068ed9baa06320a94c81d14855b72335f0020"
    },
    {
      "path": "assets/illustrations/spells/volcano_eruption.svg",
      "hash": "ee48c68787fee402fecb50117bb6ec8b79cac1812aafc110801983e35a0fa26f"
    },
    {
      "path": "assets/illustrations/spells/world_roots.svg",
      "hash": "ad47dfa67712422239e5ac2193e5fae57af3a44fa11d5e2f65fb106d31706ea4"
    },
    {
      "path": "assets/social/og.png",
      "hash": "87b369152a72e361a16ae2fc53095ad674b1bf75ae310907286d97f7db1b11db"
    },
    {
      "path": "assets/social/og.svg",
      "hash": "6504cd2b15726de6e63ba19e5ce13b73954c2ddc78d942a91545e0a5903cd508"
    },
    {
      "path": "assets/social/og@2x.png",
      "hash": "2f6c78392ae04dda6c30197635ec7ede1765839706f1b247be53f7b97eb47102"
    },
    {
      "path": "favicon.ico",
      "hash": "3d9226fbc6bf99f09c1084fe452aba834f0d6db41498a290fdfd254517dc183f"
    },
    {
      "path": "index.html",
      "hash": "37a1e5f4c31e5a822b5738f029015367f1373a461d7cc677f5ddedffd1382dc4"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "49d69f1e5829eba56fddac52b262cb392d3f3ba0d69748b1b40941f21ab55e81"
    },
    {
      "path": "src/audio/audio.js",
      "hash": "39e43d5a16a80e7337a130f69e5bf76bbedd1adf592457d8fb6fa7819f017f2b"
    },
    {
      "path": "src/core/input.js",
      "hash": "a7e0dfe0a9eba15e1630c7e57ab4cbfc54e492df133be91924991144433fefd8"
    },
    {
      "path": "src/data/audio/compose.js",
      "hash": "7a9ad12313f040bccaca73f1d8d8794a9269d8b2b71eed45bab5de484d54985a"
    },
    {
      "path": "src/data/audio/settings.js",
      "hash": "9a3ab8b5557c107b0f49549116bee6b40aa4ffe4661913dd29cc2a55b26ca97b"
    },
    {
      "path": "src/data/audio/sfx.js",
      "hash": "67e1bb42a94718c92f0ea4a61eb3a4ed680346e66beee101def7278b0176e8ca"
    },
    {
      "path": "src/data/audio/tracks/abyss-1.js",
      "hash": "7cef4c1dc46f1f174ad64e933ab6937ee716b0dbf74cefa79bc6a214716366fe"
    },
    {
      "path": "src/data/audio/tracks/abyss-2.js",
      "hash": "72e8f7a9b8e027bdf4cb87104f83a97a8ddc685500f59545f29490f7604563e2"
    },
    {
      "path": "src/data/audio/tracks/academy-1.js",
      "hash": "6888aa6a30ad78c63cfb9c9d19b3c372c214efa5c2be91040281bbb601bbe4c5"
    },
    {
      "path": "src/data/audio/tracks/academy-2.js",
      "hash": "23931553468f696dbc7d3080a9b6d5f9a371f6241f40c9aa34029706f49e56c8"
    },
    {
      "path": "src/data/audio/tracks/boss.js",
      "hash": "de2f4a11495f49cff090c7173508b1ef15cf995a1ff87f73b905536da19607ca"
    },
    {
      "path": "src/data/audio/tracks/endless.js",
      "hash": "f6c4fab83deb349f339d6746efcd6c3a39e50406de8b1e8dd8b3b0d1b17535ce"
    },
    {
      "path": "src/data/audio/tracks/forest-1.js",
      "hash": "d0dc004ccc1d8b4c7795dcb4346ef1bb6e5e60c54d4787ac0577301f1cae724e"
    },
    {
      "path": "src/data/audio/tracks/forest-2.js",
      "hash": "bfb3f1674943c5792164b9018a91eeb54d5d0693317c639372f7825b78e48ab7"
    },
    {
      "path": "src/data/audio/tracks/index.js",
      "hash": "af52cc1f60ca7a717f85c609c3ee7b0876d1945c8ece1d152e23030cb48f396f"
    },
    {
      "path": "src/data/audio/tracks/menu.js",
      "hash": "9f0c7b999bf5e96f5e65ce88a8e540679f452472ca730e15856b76ca1be9ef9c"
    },
    {
      "path": "src/data/audio/tracks/results.js",
      "hash": "57101821fcd97971b67654c08f33825853eae37e66560765aa8d57611a65be65"
    },
    {
      "path": "src/data/audio/tracks/title.js",
      "hash": "81a60e1c65d8870dd0c75701dcff0acfafb71dac9a8f63f12a496f065d5ac8fd"
    },
    {
      "path": "src/data/audio/tracks/tundra-1.js",
      "hash": "815d3925699634e74f29484f0d90a507ef559fc413c32c555f27a67b098e787a"
    },
    {
      "path": "src/data/audio/tracks/tundra-2.js",
      "hash": "8441f06c312b0758bbf247e4c96d7d223de348f0cfa861b2ca833a41edb31377"
    },
    {
      "path": "src/data/audio/tracks/void-1.js",
      "hash": "66054ac1d0693931f2d19beae03478ee43323717af0f785492d4f82eee5c55de"
    },
    {
      "path": "src/data/audio/tracks/void-2.js",
      "hash": "6145af0078183654e66cfe341ed5ec8a9e19e41073187b3cf5e6fadc58e84f79"
    },
    {
      "path": "src/data/audio/voices.js",
      "hash": "1a11557c5a665f3bbf397e95e967a33d7e5f5f9e9c3343897925d0f71bcc61e6"
    },
    {
      "path": "src/data/bosses.js",
      "hash": "a040a6a49868b0096c54f277c19b630052dcf25f132edb4abf69b81c9da4e593"
    },
    {
      "path": "src/data/config.js",
      "hash": "1c549cf68e1e0f0daaf13901c0655c0e429d2fd9cd09f0b15124d471de3c1b3c"
    },
    {
      "path": "src/data/enemies.js",
      "hash": "ab82953c2083648e5ec314ffe643d812a559af5366a17920bef10df845b17875"
    },
    {
      "path": "src/data/mages.js",
      "hash": "e0a0dc8dad34d333dbd21e3ac5104708685f8d22ef7fecf33593e7e2ae3b33b8"
    },
    {
      "path": "src/data/maps.js",
      "hash": "49c1762f3a2d84209a6803029b3c13d0b520f73adfccab0229ccb520c2d02ddb"
    },
    {
      "path": "src/data/passives.js",
      "hash": "5547edef611577e666ec0f1f116c69aa5146a6522f10676b495021feda17ef1e"
    },
    {
      "path": "src/data/spawns.js",
      "hash": "6f447b39f1d13230be0a8fdd142313d3e4b991aa3d9a48024d4cf9208eadf16a"
    },
    {
      "path": "src/data/spells/arcane.js",
      "hash": "9c3fb35753cad448215c870a5567a9bb8e04f3b16a35c511b2348b72711c09c3"
    },
    {
      "path": "src/data/spells/fire.js",
      "hash": "a5f3e8df4d33a82dce2bcb6ec47a4af9345945c70157c2c15f79a0a04d8975aa"
    },
    {
      "path": "src/data/spells/ice.js",
      "hash": "28f47285b477edccfe11194f79dc4cda264c57a5e695bdfaf8f122194d93ab57"
    },
    {
      "path": "src/data/spells/index.js",
      "hash": "f45444c0622ce9acd1b31d85765d860f52beb874aaf850f76c8d9123d3e6d522"
    },
    {
      "path": "src/data/spells/nature.js",
      "hash": "87c53ea828957a5a70929cab597f06f9e22776bdd37fee8de68efae55e4e9920"
    },
    {
      "path": "src/data/spells/thunder.js",
      "hash": "62e8f259acbb6bb197497afc82a89845d5b8dc6aa99d8d20b064b5918214e71a"
    },
    {
      "path": "src/data/spells/void.js",
      "hash": "27642db3035ae7bc6150a0aa9940a8cebb44d482275688b7a6c5b3c6bf962b8b"
    },
    {
      "path": "src/data/unlocks.js",
      "hash": "486607652173c70f3ee7d7af9cebfa0b4a71420f5d0a6bbbc0f4763b4eab0449"
    },
    {
      "path": "src/i18n/i18n.js",
      "hash": "84fb8a2f3abb05acde6fd0d6fc02b7f40d41f6228c215962b246cbb2a5783b47"
    },
    {
      "path": "src/i18n/strings.js",
      "hash": "50753aa0587db51e759794bd094e560d944b2a090bb784acad48dd0fba4d809a"
    },
    {
      "path": "src/i18n/ui/codex.js",
      "hash": "d5b74e0c3dd8300eed082031c529478ae4d5527007064318a8223e802f56b8bc"
    },
    {
      "path": "src/i18n/ui/common.js",
      "hash": "5f117f497dbc8f5dbcdd7dcde742befd0530f1aac44e8748c2e0902b5756a06f"
    },
    {
      "path": "src/i18n/ui/game.js",
      "hash": "56ef559b28a8dda203721de0829f05fc573749f28bffe584e549c10c4cb04d04"
    },
    {
      "path": "src/i18n/ui/howto.js",
      "hash": "5fa181a5ebc264d9768525a2b5fdc74b68cbb2ee913bea742fabacf2aaeb1f20"
    },
    {
      "path": "src/i18n/ui/hud.js",
      "hash": "4f2a2584bb44c64be63b26a96af4066b04c6c22dd2e8faab14ecb6fb197e3364"
    },
    {
      "path": "src/i18n/ui/leaderboard.js",
      "hash": "e4f13f48cc0a00aaefa404e40e59c7155186cc31cf2b5d73299e7845e42468cf"
    },
    {
      "path": "src/i18n/ui/levelup.js",
      "hash": "15f7c8765046ce6bf5f3bcd522755a4a517037cdff37f4e6fd5da8064ea64247"
    },
    {
      "path": "src/i18n/ui/pause.js",
      "hash": "1cd59b2dba529deff9faa7d878bef7b650866ced44343e8f2d1cef394d2b641f"
    },
    {
      "path": "src/i18n/ui/pwa.js",
      "hash": "6d1e36646ea5ecc1901ef948fa49869273278a066fd2ad4a3cde92bcfcbd687a"
    },
    {
      "path": "src/i18n/ui/results.js",
      "hash": "ad27cd84ff178fb5aeedcbf6dc503d10ec9eb83cb25130c7173151ea747ef16f"
    },
    {
      "path": "src/i18n/ui/save.js",
      "hash": "0130fc09856d3afb58facba3a746f3f9bf934ed5e5e07e31c69f894bb1bec6d8"
    },
    {
      "path": "src/i18n/ui/select.js",
      "hash": "985d228837560b4bdee23d6d2a3c7f685d0181f9c6ec9a96cbd6a98b4be894a6"
    },
    {
      "path": "src/i18n/ui/settings.js",
      "hash": "b1daa29b7c70eece38d8f0ff94230e146c082bcbf22d5fc2308af2a35049d547"
    },
    {
      "path": "src/i18n/ui/title.js",
      "hash": "19751dca48f79297ab175eaf77ab8aaa262318cdc110d771849b53eee44ed43f"
    },
    {
      "path": "src/meta/leaderboard.js",
      "hash": "20efa61427490db62a135008a2cd4f638675a5ade09a037206308764fef896ab"
    },
    {
      "path": "src/meta/unlocks.js",
      "hash": "6b1f7b3d00fee570578175470923638bfcc0d5e6e4b5e760249d4e585f9c6eb5"
    },
    {
      "path": "src/pwa.js",
      "hash": "c7645786a5b4387b0681c1688bd6812fa7b9ca31e505bc74dca68cc93261f9fb"
    },
    {
      "path": "src/render/battle-view.js",
      "hash": "91548a7e97e9665b69a93674e5579685fb657758b16ec6ea8b29556d24f0f257"
    },
    {
      "path": "src/render/colors.js",
      "hash": "726f17a0cf680c144c852f239df9e6aa931aeb47dc54ff2f26bb6a5f2d192b43"
    },
    {
      "path": "src/render/damage-numbers.js",
      "hash": "b949a18e5ee996796059c54b809a7076eaa3ef96db18b0115c83f703149333a9"
    },
    {
      "path": "src/render/geo.js",
      "hash": "45fc08272f5b56bffa4282c2b4e6fa706a792571c841f732174c214d4f28dec7"
    },
    {
      "path": "src/render/maps/abyss.js",
      "hash": "b2f447779b45c1fb3d6db2b897ae8ad6b9aff65c5cba3c2d2f6a9749fb7efa01"
    },
    {
      "path": "src/render/maps/academy.js",
      "hash": "02da885ea78af0f0863dc17d44d8e7bf244bbd77aae87b1ac829917c3333864c"
    },
    {
      "path": "src/render/maps/default.js",
      "hash": "fc7be5d1bade95e2d2373230326b185ce8c831eba6067f7cc34148f7cf732437"
    },
    {
      "path": "src/render/maps/forest.js",
      "hash": "c8c3467a5c191f1866de4531c30d805448abd345cbd0abbda9963b4cdcd376ff"
    },
    {
      "path": "src/render/maps/index.js",
      "hash": "3a28965dbd59ecb0ae234ca4300ad80b43cceaed9a53c7d37f138c8cdc19ba98"
    },
    {
      "path": "src/render/maps/tundra.js",
      "hash": "ba4349dc3fbb3c8fd2e107dbced94cf0cc52a67a60d6851e385714e2277d5616"
    },
    {
      "path": "src/render/maps/void.js",
      "hash": "b6e93e7323cd27bb9ce984c6c55ab6d913033ebbe58e37ee297d2c801cec6229"
    },
    {
      "path": "src/render/materials.js",
      "hash": "27f95c6f0daf7b49e2189210c4f643f0c4b7c4817f229fdc199e08f2a098a7ad"
    },
    {
      "path": "src/render/models/bosses.js",
      "hash": "fb0c3d55bbd8cad341f4edb6e4185f7eaf15e0a0535029cce1c28b5e7f84156b"
    },
    {
      "path": "src/render/models/enemies.js",
      "hash": "b892d67faa7e4c2e59ed57b04a19633e0ccb02218fbf5ecefab523d11159ca2b"
    },
    {
      "path": "src/render/models/mages.js",
      "hash": "46c713e143574ade3a59c2016dfc46282b084de287f824167b4d3b9ca37c57ec"
    },
    {
      "path": "src/render/particles.js",
      "hash": "7496e826d77037bf00f249aedd132ccc8b0c2e8bf91c8b423b9da1db3490038a"
    },
    {
      "path": "src/render/pool.js",
      "hash": "716503badc4d7f5db57f5025523e6d1916118fea148aa19e92a3a99e8cbbacee"
    },
    {
      "path": "src/render/shapes/arcane.js",
      "hash": "3c5188c91b589d86992727f631cd47562eed7037cd6f9b18a9a3b82c52f2f242"
    },
    {
      "path": "src/render/shapes/fire.js",
      "hash": "2b039108ae3c9be7f27b0ca3082c7bea4a59dc5044b81f9ef642dfe08182cc57"
    },
    {
      "path": "src/render/shapes/ice.js",
      "hash": "6587438ab9c1a7ffaed9d4bbe2c9cba2f95d75d26c0d65e2996b9f8a958418db"
    },
    {
      "path": "src/render/shapes/nature.js",
      "hash": "f75e02c2aecd1b2026ef93816c5b7e98884fbbbac4e4046fa197c0fe7337a8d1"
    },
    {
      "path": "src/render/shapes/thunder.js",
      "hash": "22689fd30d9c44398b8e67095d00c4950f8afd5bf08ece6dbc0d136093f68d62"
    },
    {
      "path": "src/render/shapes/void.js",
      "hash": "5745aa0dc0b3d091233286f286f9b0f73c33aa052dd7a7b3ccf169bdf6651bd1"
    },
    {
      "path": "src/render/title-scene.js",
      "hash": "a939ff23cadb332f5f8da67af9b1e437bbfb51876c33249adef4cb13597b505a"
    },
    {
      "path": "src/render/vfx-shapes.js",
      "hash": "93269664239f074837a4d517afbe69c7f87dec9a6146c8e9f08edf6325c43801"
    },
    {
      "path": "src/save/save.js",
      "hash": "466a0605f067d3f97fc8b46b00799eea2bea7bb471fafc9939dc84b8555ea0e4"
    },
    {
      "path": "src/sim/boss.js",
      "hash": "d81a522f24440e0ca632d47d34c4685c39eee419ba02e79ddac60b2b20fee689"
    },
    {
      "path": "src/sim/bosses/fallen_archmage.js",
      "hash": "1a3f9a9ea82c5b891adb9c86002b70a57d68f806ee8ae87e95586a582f2cc5a3"
    },
    {
      "path": "src/sim/bosses/generic.js",
      "hash": "882cd27911fbd44fe83eb4ee7dcf78a3e9cd2896a62f7acd6658d209ae979c41"
    },
    {
      "path": "src/sim/bosses/ignarok.js",
      "hash": "88dea844f282813aaf277de73fe474a9cad627a2416eb0021a5a7eb5cc138fe2"
    },
    {
      "path": "src/sim/bosses/index.js",
      "hash": "ea181e842f8e8924fd06294b3fce25634d73a3e1bb9649b1e1deaaddf308080b"
    },
    {
      "path": "src/sim/bosses/kit.js",
      "hash": "5b4b560c148a1d60dc20cd6a22a01a1ffea0d26d9e1f051202564c9a3c62d6f8"
    },
    {
      "path": "src/sim/bosses/nullgaze.js",
      "hash": "217a9696f3ed7682d5689b85c2e257141a3a94ea1923b207cd7aec80b14cca54"
    },
    {
      "path": "src/sim/bosses/rimewing.js",
      "hash": "a6494b79a79d96c0115a35d21bb0dfb511ced6b34cf0efd76b9fda1acbd0dc5e"
    },
    {
      "path": "src/sim/bosses/rotwood_king.js",
      "hash": "b22c2b102562feed46ca64b52d774882350c1c04030149289bbbdb79195e3a64"
    },
    {
      "path": "src/sim/combat.js",
      "hash": "0903d625adc5dccf387d75877cc49ff2aa1e070fd48cb53a56c4ff6e0e4141ac"
    },
    {
      "path": "src/sim/enemies.js",
      "hash": "f4f255c6e3d50ab8bed10a51fb146d827838562ff260b79772a059c7ea5d949c"
    },
    {
      "path": "src/sim/entities.js",
      "hash": "21225d6a8d9b4b1428049b0054effaba07d165c6e6af9b6b16e0a3a740c38809"
    },
    {
      "path": "src/sim/hazards.js",
      "hash": "26a2fd3d526487a760220f9fb4a1e67072d16883b3b3c988c7a2f378c508f997"
    },
    {
      "path": "src/sim/magepassives.js",
      "hash": "b0df985c89780cf8178908517237591b4137b28641413228f5356a81ba961fa0"
    },
    {
      "path": "src/sim/math.js",
      "hash": "09d5d52e7257934a74c96cd00eef13b3157c184cac992b45c949171e43871ff3"
    },
    {
      "path": "src/sim/player.js",
      "hash": "a458e13d05fce649c8c23aa8f6e15a2268b2f79a7a00d85c2721ecc490f4eecb"
    },
    {
      "path": "src/sim/progression.js",
      "hash": "43c6c5b7511638bdf74356c921fac59669243d0f38889acb00e9248931526e6b"
    },
    {
      "path": "src/sim/rng.js",
      "hash": "c1ce2f80b8ae68d22e51fa21f1c33196d520253c6e72af14bcac1369515de578"
    },
    {
      "path": "src/sim/run.js",
      "hash": "74850b0460b414df1e26d5532d4d612c76f5f45196cea4818ebf065b81241667"
    },
    {
      "path": "src/sim/spatial.js",
      "hash": "8d4c274124ea22c0a0e8b2995e2b40066b0445fa48c8560862e69d919f4e6cb6"
    },
    {
      "path": "src/sim/spells/arcane.js",
      "hash": "f4379b2906a07920f442ccae8c44feb52a22beda8503afcf2013796f71b61044"
    },
    {
      "path": "src/sim/spells/fire.js",
      "hash": "06df31116b1d28bd27f3471fe476bc92ee25051295c29fae9cd1be3e9549062b"
    },
    {
      "path": "src/sim/spells/ice.js",
      "hash": "f1bd8c107d752cdcd9839d1c37330cf30b12c27bb8af05c510f000c036f8202c"
    },
    {
      "path": "src/sim/spells/index.js",
      "hash": "00afa3b804f1d3e5c2d199ccf72935762a6f996e96cc4da043f036ab68cd55b8"
    },
    {
      "path": "src/sim/spells/nature.js",
      "hash": "e21514bc5c121fb9337e539ea92fb47c2559c370f98300fd5ddda9deca6cf802"
    },
    {
      "path": "src/sim/spells/thunder.js",
      "hash": "7ae9ebc6704ff57877c972ab5df3d4518b528cd897d2caaf45b05a6506e50779"
    },
    {
      "path": "src/sim/spells/void.js",
      "hash": "3d011fb91e2ae2f7eae7168f66355a6883dc026b537fc277bbb2cbd5adb6c56e"
    },
    {
      "path": "src/sim/terrain.js",
      "hash": "3fbd4c7ace7e995ccd48eb6d5d1f0fa6e69ba8cdf9462a49a2eaece9d341fb46"
    },
    {
      "path": "src/ui/codex.js",
      "hash": "9c255952242d580a7d4672ec21c9ab07c78585f40632c7c4c8f35da30db3cbeb"
    },
    {
      "path": "src/ui/dom.js",
      "hash": "d952051224af231456dc57f77b81a5fac33d52a5e90f46b0e4f821c687024869"
    },
    {
      "path": "src/ui/howto.js",
      "hash": "88eb22d62cab37eab92c926cba1228435ab5b1330191c0f330ec8b46a4ce382e"
    },
    {
      "path": "src/ui/hud.js",
      "hash": "00939ebab985f9b551b5ac1ec429c7cb6f37c39f4ce951e5da0fb16124fa555c"
    },
    {
      "path": "src/ui/leaderboard.js",
      "hash": "139aacfb49ce6618d5164dcef2dcd57d62e6818a56c8b86c635157ddf76c77bb"
    },
    {
      "path": "src/ui/levelup.js",
      "hash": "7be083ec26004804f7a485198addf20635b05469ecf431dec2d8b5cebf1ed6b1"
    },
    {
      "path": "src/ui/pause.js",
      "hash": "0f6cd9cd2a13c95f74470125e1f17f9045529f976380d39dd4e10c700dee8acf"
    },
    {
      "path": "src/ui/results.js",
      "hash": "f131e1273848e55af8071728ef0faa6cfcd166d8d35e863b91a24f3be6ba18f6"
    },
    {
      "path": "src/ui/select.js",
      "hash": "f2abf73b47726c50c0d602e2d83603122cdb4dc9c2a3d758b82f0ddca4a73518"
    },
    {
      "path": "src/ui/settings.js",
      "hash": "7f46b201b1d877314b29612a40033a95e0d617dc7a533477f4bd9e5e7e0d4646"
    },
    {
      "path": "src/ui/title.js",
      "hash": "c48931f664a45dc5bf3a13296b49de40f5cdab9b37793166244056cbdc6fb542"
    },
    {
      "path": "src/ui/toast.js",
      "hash": "1c0e3d16733caf4e40f3c94021b7562648f474687ec40b39f8c814804f1edbd2"
    },
    {
      "path": "src/ui/volume-panel.js",
      "hash": "f44c9362db901c6da9b06c8fbdace5e2d23ec13cde1e50fdaedb78c931c105ba"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/asset-bundle.js",
      "hash": "7d5fb5a967f146b108ebcbf5f3a608337d038695d04c9ceea4bc3f449953089a"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/fonts/bitmap-font.js",
      "hash": "1c7637de673fbe35b9e8d0502e9d5c11073abd4bd70c282d4d2f58b1c4a51e65"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/fonts/font-asset.js",
      "hash": "0130aa9a7cc6a2c8bccc6e6df56bc104fc58329858334fb89a840389ef4f3218"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/fonts/generate-bitmap-font.js",
      "hash": "6eb49eaae3fdc0f8890ad3d923b7711a25fec52d460ac4f74c093c543710424b"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/index.js",
      "hash": "30d387c84f50623e39b575bd8339040a113471c6bf6347f8d0af7377b768a39a"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/manifest/asset-manifest.js",
      "hash": "7a2a8b1364ec33c2ba9fb6bb4c0fb8f8858cc10e01d7666bc478bafbe9957c4e"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/native-texture.js",
      "hash": "30acce9a9b2ffbad6e50ef5e3f9261556d98546c3e4e8a5647e74eb767901661"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/preload/preload-batch.js",
      "hash": "9d06265fe9007aebc8096b6d748525be656bf6d8a4bd8932e7130f73fc35f378"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/preload/subscribe-load.js",
      "hash": "9bdc6eba8e4cc9c46fc835d721c0f589582124faa5d4ad58819aa97eee3babd5"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/read-response.js",
      "hash": "745725010596a63a03e2ec8ebd289a7200f7a6eabf0b84fa0174cd62f14d9c19"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/resource-scope.js",
      "hash": "f7d90cace9fb2585b5fffcdbbc69ee4c984282dd5f1dcdb8f34384fe6c942233"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/texture.js",
      "hash": "734e9903f6a81d6ed0898c9a8f9b661d40d6ac5190304a2a1843bd66949dfa77"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/texture2d.js",
      "hash": "724bb1d7d5502430ee1462da764aab5e5446b2bdfd960d67c06275526e77e79c"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/tiled-loader.js",
      "hash": "4cd50ab540fb629ac19bbdcc9a20fc952052026dd8fe7da1ae269a724e263fb0"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/tiled-normalize.js",
      "hash": "b1255eb514e28092256c8c51816dada74ec9461a647b064093ee451e311d63ba"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/tiled-parser.js",
      "hash": "15bdb2c2db04b21705eb7aaf11e46c774d0c887f4ddbee4e96abcd6a0e1a73b6"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/worker-job-protocol.js",
      "hash": "aad76336ff45aa0db123eff24d17307fc86301068fe7ad40b49bc32b958344a1"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/worker-job-runtime.js",
      "hash": "2a7ece096cfb0b1ac9f55e01304ad23d7130336d00ddd857ad124734b1186c97"
    },
    {
      "path": "vendor/xyz/dist/packages/assets/src/worker-jobs.js",
      "hash": "a47f2d52b761fb41b6ac953a7c8c6fadb2edade1eb505a53464f2f7a4f1243b6"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/audio-manager.js",
      "hash": "c1ff10671dfb00f441e193c0abe0bf1478b9109e4c3ff0c1f9d5e7a59a5d20ec"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/bindings.js",
      "hash": "09d62990c218ffdaa70083278a243bd12e7a94f70265f52e82b7cc623844028a"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/effects.js",
      "hash": "f463399b69eb2c03b1a5c58b4f76eb08a922fdc38f659cd1e547546828ffd20e"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/errors.js",
      "hash": "a1046ca0401e58d29f85add09a257c54546a772f6842f8cd26d9321d3da79220"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/gain-timeline.js",
      "hash": "5d6994c66eb2ce65905e752b1af72f8f4a53a90d878ced8d94f7342b8f0670b7"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/index.js",
      "hash": "b0a9251871994ad40d1e05c11da3643fc2b33e39fdfcb8f9ccac818c76df0f9e"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/mixer.js",
      "hash": "33d7f84bd75f2038e5278bec5ca9472f9fcc3691c51ebd98902aafc2d6622d92"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/opm-adapter.js",
      "hash": "07739237b3dbcff21a3b7324374c662532352f0521e403caaf354cfd5cb43a5d"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/samples/sample-audio.js",
      "hash": "8a2d05ef2353dfc7427fa2da424eb883770143467e28cfafca10111b00f9475c"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/samples/sample-playback.js",
      "hash": "cdfaab72a598358aa54eb28370e076825004d0b9f5c1b100fc261ea36e8be655"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/samples/spatial.js",
      "hash": "2b1364ace8134ceda4f5fa71f2a0e06933b57ed02915b06ef9f71eb590d145a2"
    },
    {
      "path": "vendor/xyz/dist/packages/audio/src/samples/stream.js",
      "hash": "138bf9d13e02c8b947011c52951193a8c1339fd81d8f8b83cded12b0e1e7c8a2"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/accessibility/index.js",
      "hash": "a3fc05331931bf158a7ead04b6f1b722364adfed7da0dd569f4322b1f08332f3"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/accessibility/preferences.js",
      "hash": "62a6c3eb831340c1aa9ab9d3490811b4897b33dad855fe0dde6289e7c2b5ac55"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/accessibility/settings.js",
      "hash": "415aa8fdcaf7a4f17e227516c3dbd07f6218a1e707f0ce8cd28ba5c610bb6078"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/actions2d/action-queue.js",
      "hash": "09208d11488ce8b61633ab369d874edb9495f4938f3170de9347c4a1701deb66"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/actions2d/actions.js",
      "hash": "998f90bb6cb090999d89c40f0e149a93f6fd82736eb3eb0bed73c366b91717e1"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/actions2d/easings.js",
      "hash": "5a84f598727d89386c094afd1dbcbffdb32f75c82899c33e215395bc1285de24"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/actions2d/index.js",
      "hash": "423bfb5f5bf75062f8c12338fbf54546e0cb1f3c914d9f79817d048af4a2fcf2"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-blend-tree.js",
      "hash": "be5de313f40801133081f5be29182c0d412e2ca1ed9fc4be4cb458da7aa626ce"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-ik.js",
      "hash": "7851ebe059e298c91436c0afa2f4af2fc35866a4be4764a73c7ffe9a6d0a52d3"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-pose.js",
      "hash": "86dbe59c830d98c43797d0c5ccbc49fdc1cf47dbd60a67151d3184ae0706b486"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-retarget.js",
      "hash": "eb25ad67027013932caaa3b1ecdd39c96cd58be4b1b82bd1a1219b5c3a059963"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-root-motion.js",
      "hash": "d7dcc18cf54c70f7b95f195bf3c7c65a53c99e37de371a4e81e2c7159fb26b7c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation-state.js",
      "hash": "e6c2da948b4a5002dd12fc6abb480f74750a66d68b4a241d935f52d7ad7e5f67"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/animation.js",
      "hash": "0aae788b1e5380747093226cc0ee0e257fdf8308bdf36ff9f00ff0347483d0e5"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/autosave.js",
      "hash": "dcae40d6325c0d89cb15bfffe2aa6fdd40cfdbaa76c0d37f41dfa055c85d31d8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/camera-utils.js",
      "hash": "f77569c7344833076805bbee82edd5234a1927ac1f528e054ae2008bc37e3556"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/camera2d-behaviors/controller.js",
      "hash": "10ee628b25310ed4e29fe7b2d1f9027be40211753fbba34954d1e3fd74ed8b0a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/camera2d-behaviors/index.js",
      "hash": "ff11d57654d45e483989815cf242d02efe313cefc48ca395bdea240856d98794"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/camera2d-behaviors/strategies.js",
      "hash": "7d56fd1b8d2ae042d5553981c692185284c89fea308dfef3a78d3ff1c1b7253b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/camera2d.js",
      "hash": "5deb52b3f982d62590ecc38da5837f0e99caf56c582b805fd51ec49732ffd60c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/clock.js",
      "hash": "19a2d20f671b25c40da37c71c96d00c4c5d8094fcab7a76f2052d1ea857af6c8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/content-storage.js",
      "hash": "89ff1d8d11f0b0af15a340c1c29a1e81786025364c6f7cfacb82d5af50b1d702"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/content.js",
      "hash": "2c6bf6e0269dd01bbc02e2506ab3a4fb3c288a1e66f6571b15733e4014b4e027"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/debug-overlay.js",
      "hash": "6cdf8fcb2bf7a697ce01e2c9f26fc1456a2cdde0197da1a850caa17ccdcd4aa8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/decal.js",
      "hash": "878095bdde6a2e504a3afff8d9b9954d43a273d08f6181cc84e28432dd196138"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/draw-order.js",
      "hash": "162fdac5374723fd196b322fd2a6b10cd36db42f4d92fa8561219930992dc515"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/environment.js",
      "hash": "3e1adeb859e31f011dbe335010cc7f1063df74deb0c6c1e6a8f34f88e8f59870"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/errors.js",
      "hash": "5bc8a559653a92822f31885727122b0b107e60813614151a77cf11eae7bb853c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/event-observers.js",
      "hash": "e171fdbdcdac55f4478c17e0e8ddf7f3a92fa8f0ad5157fca5479cf6b08b8dd9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/factories.js",
      "hash": "8ac024ba586f1d050de52e85a3dbb6384946843e0367e7eb4b718ce2982ab4dc"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/first-person-controls.js",
      "hash": "18f44a207e19a09cac4f83e83d60b7dd4587ff0ccfdaf842e51e99cd738090c8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/frame-work.js",
      "hash": "ca2c1f239d6084226fddc377ba2a5e6f705a32493eda56283d8c44a67b470e55"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/frustum.js",
      "hash": "af7aaf174a753fe707292027d16b7ee93cbdb80a21dec8ccecba8225dc8f4118"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/game-object.js",
      "hash": "877b483fbf04eb4857895299daac421c57c341f1ac4bdc501982d78112c96cf9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/game.js",
      "hash": "9a7cc5442e96b894e63595603b02066f733c7b47ebe3505e3a1c54bc96502f19"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/contracts.js",
      "hash": "56e098a8e25e5a69484fd669ca9f4c33046ae6472189bf87c8fbe4c5abf87650"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/frame-animation.js",
      "hash": "a8e8cf6492c2091813358ef6076aa15d0521214dbcc9b9fac88ba630a61f205e"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/group2d.js",
      "hash": "534ef5836f0b8e3da8c12d465c4277b76bf44587209e858edf3158e816516dfb"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/hit-area2d.js",
      "hash": "6c3339c33e9db3b80d4d4abe911939e501458f3911356a1cc333f573135ec7a4"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/interaction-events.js",
      "hash": "433adc340b71c8fb30861d3a1e57f24653c3b1044f75973f9ef2322d94667682"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/pointer-router.js",
      "hash": "ae4cdc956680ec5cb4c1d79934c7210f571e2a170cf1bfaa1f49bbb16128c514"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gameplay/screen-element.js",
      "hash": "2a18e4821ced987f2ba7bd20b44c2dfb2b059b11a4d1072206d6a5f0b8e21cd9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/geometry-processing.js",
      "hash": "69ee41dacb5343d14eb9cc4c557a883fd9429b1d024b8c2f97e21d90bf4eca40"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/geometry-worker-job.js",
      "hash": "495bee17c666adbd6452cdc9e795131241601fa52727ac66bb8e4038902bf830"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/geometry.js",
      "hash": "b573c768652da52f0439158da80edba9c3e73b4d0293fc4b39c8e33b21e5bf0c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gltf-loader.js",
      "hash": "8e2c7d9a02cdbaf2518ee7b2a00b9059d526ecc4fcb206b156d48eeb0287ba1a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/gpu-particles3d.js",
      "hash": "1c9cec9945bf3a457e6ca4272a2891191bedfa1fe1fc3f33398441a252d9f1c4"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/atlas-loader.js",
      "hash": "6dd635b7581d5d889b357a92ef747e1a58315799819284e497d3da5aeb0a840b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/graphics-path2d.js",
      "hash": "c1c91520405d234b61a06c583818e7762487c0816321f1e75dd1440e41172ed8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/graphics2d.js",
      "hash": "ff91d690be56b266c4e5b30ce0eba68e8aab6709a8a110bc4658bd8facede5e1"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/index.js",
      "hash": "0447e02424ed019e04cdb8a0f7d1ba6fd763b66f15f7a8203894f68ee0b56fdd"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/nine-slice.js",
      "hash": "7f93f35b5096ff88ef11437b87d6e4730452130be7894b02bda993e97afbadec"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/sprite-font.js",
      "hash": "bb61cbd28ab432dfb6896f6cde741319dca7fe99639cb07ba6c202773844304c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/sprite-sheet.js",
      "hash": "7349d3226c009fb1acc4b4ebba62f37a479f7e1b1ed64c2e920fa852c3846c21"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/graphics2d/tiling-sprite2d.js",
      "hash": "b995190a214576afe03359ac0c706207d84bd56e150e16ce05b3422c8e6aed16"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/group.js",
      "hash": "a3e3c82bb0dbef9d4db5b1085c7fbe3198038bfa42a704ac522a7ee62f2963ff"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/i18n.js",
      "hash": "e08239033575c28ba0a82a30c99d86f9043e2b63f882d230cf2f4bca395628b6"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/index.js",
      "hash": "10ac595ed17cc8a118c0191e6a545521159eca45508a4ec0fe812d4f68643083"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/instanced-mesh.js",
      "hash": "ba760395df7135475b7e6bc2167214f506178873f78285b75c81a036dcaf19d9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/ktx2.js",
      "hash": "90cd40574e8f2405bff8160d33ed3bdf1a2e93da9ddaf5e8ded6a92105690455"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/light-selection.js",
      "hash": "f9c1546747b8f819e2089438d61de548d0ab3842ced906c1682ab8920a51d750"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/lights.js",
      "hash": "819c686186ef4415549dd0f67a7e1836349f1ffd3496568b2016c42091b9a205"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/locomotion3d.js",
      "hash": "7991170adf6627024f1f5d4f1fa9373792994b48c5118af1fe10bef60fcd1f23"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/logger.js",
      "hash": "7a5a927c2333c05435b3359a14cf46c5f0b6081602e42043bbc8f2916227be3f"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/maps2d/index.js",
      "hash": "bad9180de5e799dc93b39c6bec459c1190679cbdcf64c21e475e7f8ac7f342b4"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/maps2d/isometric-map.js",
      "hash": "6f9a792785e1528a3358fc0a97b42068a658ff2d04ebcf2ebb5f4e408ce31692"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/maps2d/tile-map.js",
      "hash": "a46e33bc275e370945c658c75ed6983dfadceac54311e5a1f85ed830b6f0ef9c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/maps2d/tiled-content.js",
      "hash": "7ecaed48108b2b47731d523b3c1a7e8b5e4a5b0f7f9d6e7a718294234510bdfc"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/maps2d/tiled-map.js",
      "hash": "039c68e1f1c2e1cfa523217529f8e90af67c51ce27947f77dedcd7d4df269607"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/materials2d/index.js",
      "hash": "b0306662a54f352f34bf1c30279a482a5e14335e595166c0796070baddada22f"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/materials2d/material2d.js",
      "hash": "afdb14f2c805b6900a3d9a31cd48a1fe79553b688dd57384fb5b538323f12a81"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/mesh.js",
      "hash": "dc8a6843ada18ecad8df151d0c50b8109ecfe53b7b9f83cd121644de7e019eaa"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/meshopt.js",
      "hash": "780ce2501605462c07deef9c8d09218c22646272f5b1f6db8ecc28021eb32edf"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/morph.js",
      "hash": "f2e2b68b5c34d891ab2c98319cd6993149c8f2291efc2c01b204044c2efdb2a3"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/native-material3d.js",
      "hash": "144b15edc2f2719f27a5bb294e11c519e9dd5ddf4321ed379c8203c237d6fce7"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/bake.js",
      "hash": "58c223463431b2da93e392f57afc6b2e7facdb3df66ef782850b93836b5e9427"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/follower.js",
      "hash": "2b35926e78f1884f42f24ca11db774301f25fa2eb417146c3045ffd415e35dd5"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/graph.js",
      "hash": "9fc480d094e84a1cfb6b92548e97f950882bc191124d8c3d88de2ae532815946"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/grid.js",
      "hash": "ad1d740ce523d713b4277b7c2faae831849421e947211ece67fd0c7e82c3688c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/index.js",
      "hash": "e9a907c099d69ca73466b0b967751c03970cb8149870d6edb0a879f26017a0ab"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/jobs.js",
      "hash": "fdf7af1bb5ce238409601347f1649f5647ea87e0da51051a04f900a0055e710d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/mesh-follower.js",
      "hash": "0f8134da221fda809882b110b68f05e62d25a243892a8e678202fcef4d8464eb"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/mesh.js",
      "hash": "b72818f390afb8e69a42706da6a44de2e7f85db654b1aadbfb9c1102b55bab30"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/partition-search.js",
      "hash": "d2293ffd1187553bddad5d0e7fd6b6c43a35425a6e634cdc2775c3a02bfe7557"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/scheduler.js",
      "hash": "3d4f9b2d14fb64a4d29517aa9d22ce8723bfe33306a9067fd8011b95da07bc7a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/search.js",
      "hash": "7979dc0c5d2d6c0937dc143b2471d1e1dab0d7c09192a287490c09df38f7905f"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/navigation/tiled-graph.js",
      "hash": "455705fd4c5143f22443c0af8640b5be197bf6687e5970c931296d7743add042"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/object3d.js",
      "hash": "e19cfb854bca730c539f3e536867c92d75628590b6dd83a8feee60a3521f5759"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/objects3d.js",
      "hash": "d6a5116bd5a8b998682d2b0a703737328728cbcea36774960798e571ee06542d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/orbit-controls.js",
      "hash": "30e50ae2881958eead532777f33d2ee0fdcfe8bd3f1ccff59af75973140196ed"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/orthographic-camera.js",
      "hash": "4e2adb9980d65a689bda27eae347c81cf7a6d4b3be4a5dbf1c37ee543b3a45ce"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/particles2d/index.js",
      "hash": "034ace557a9121958487f31d9c61d77c297904ced5a6b332c810275bd7373f7c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/particles2d/particle-layer2d.js",
      "hash": "73bd2726046cc9325c50f088d158b53ab1cacdc18814e08bfbc79b995a246482"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/pbr-material.js",
      "hash": "c04e6f532d1b84c1a284a9d55802f74c1bab95d15d38755aff85bb016974aae3"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/perspective-camera.js",
      "hash": "c09742361e97101fc11d33f58c85b94a681469a6705c2cf9556d5d8f93795f3c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics-force.js",
      "hash": "230d771c1f02fb6e3245be4e496b88d60049081017a000a931436ac26c1d543a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics-presentation.js",
      "hash": "abfd2d2ce5b7e83fd5a6ca63622a5c17b187aace05a0a1b8b520aceed1d5ffc8"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/body.js",
      "hash": "417e52dc8b2c55b8b1a75f4f3c994fe9f0469f995dd6ce4140ade5e7416bc637"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/ccd.js",
      "hash": "c9f9e8dc7ece663e36c8d289f12bf61feee25a1106cc78f05b10b0345174f6a9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/character.js",
      "hash": "52d40fc4b4fdaf7ad7e49e89b6a921ec6c0d1c5987114665bcc7a57550cfad62"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/collider.js",
      "hash": "b3eca3de3a2c8b281db40d312a2ba3b63bf1c959c784f3c36fa7680580fc4441"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/debug-draw.js",
      "hash": "aa968c3a3e6a568280b9da549108e041d56b0c79a264c8744f64ab7fba40e7cc"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/index.js",
      "hash": "a299e7f62a29d6a38543af5bc7252b5e6ba0179c3932aacf7724c450aa4e8850"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/joints.js",
      "hash": "eaeb862494c9a36d0693a27b87c93a4ca93f91d76e436c9b24a1e5a19661aa0a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/narrowphase.js",
      "hash": "67a1ddcc11fd11ee848bb1af97bb46eade8cd0188a8dcfffd72dc34bc5498c13"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/shapes.js",
      "hash": "f2e6774a54cce95add4028648e18961407c62a81c0f4baaddfd94090bbc95522"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/trigger.js",
      "hash": "4fc400fd6d7f15a5c44404f5ee54b8c7898b05ebe2e4d36c55fd8ebd03a0360c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics2d/world.js",
      "hash": "5a1ed712c4231fbe358290250361f9b399cc144e363b44867dff50a8baf1964d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/body.js",
      "hash": "00d6d306b838a358cb3eea42873c2b36ddcf43ae0d0dfbf5a92c512be9f7d97a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/ccd.js",
      "hash": "de434ebac272b6b82949b08b280f850ddb67c7e2a143ef3d2335460d8b2cd294"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/character-support.js",
      "hash": "53dc6f392d415b8fe609c67b198598a777c6f3cf077badeef9e5635e145b92a0"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/character.js",
      "hash": "fcb5ee00ea0c959542f29358f0c595ddf7b55dafff6d18c77e23ca7134d359b9"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/collider.js",
      "hash": "38a7b634bc6ce45d491d2836a823857ef0482e457f80fe671b8bf6d5faf74a7c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/geometry.js",
      "hash": "58f9a552c763aba1b54e3ca9a8a46af86c6d07b795514b0d2a303a0a29dc1d62"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/index.js",
      "hash": "bbe9e85c9b4812e99eb67a2eceeed3ef1e9772f8280a399403bacd1b68602913"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/joints.js",
      "hash": "1d047092b21c0c02408933d7eabeb75b2265a32760198edf244b3fd24db0b9af"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/ray-intersections.js",
      "hash": "a928ce29404b5541dbde65137dfbd9c7a72b8036514c84dbda4e13831c5b361b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/spatial.js",
      "hash": "573564992d0611a2b53ad8cb977c140a8d2d12cc6b270f58c7635720c517a5d6"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/physics3d/world.js",
      "hash": "c4cc849f9692ca268df3c20021de39de0162461726bf7957d7d5fce434a8ef36"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/portable-save.js",
      "hash": "59aa2363ea83bb394091605d72190e96a1d112c7ddb4242d18393d0bf1edca7a"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/primitive2d.js",
      "hash": "4e55f156986b7c31d11f22709d877244857df1b4f330d68e37b89fa10220c051"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/procedural-material-maps.js",
      "hash": "6cff00c141beb52f495c573a38cba44a03c5488492d822620d380a6cc27dba26"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/procedural-material.js",
      "hash": "f5e22b5e61266b4546375b2b2017519757129060cbf595378e86b55ac6dbc415"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/raycaster.js",
      "hash": "6d483b74f8bfdc4a954d54fb51a6c262ad8aba08a288ede180ea4b1bf4393521"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/reflection-probe.js",
      "hash": "1e3514ac4ed5fa502b0ff218314e00fcb7ee6f2f7aa3164f0a4663780629f29c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/render-bounds.js",
      "hash": "f047e1155f36e3b43bb134153fcef0e5918a5cde9326edf9a623d7921906ba6e"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/render-data.js",
      "hash": "f612f756fda4eaf109448138c4e7f73291725ac1d4c2556ad7ed21a06dca4754"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/render-settings.js",
      "hash": "06858228cd392869e74e6913459cdc3db572099885f97be1ecc3d8f8fd68bb6c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/render-visibility.js",
      "hash": "cf7a8aaffd3dd7ac8c1b1692fb437c07c26f97219c6fd34de18a67523afc09bf"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/filters2d.js",
      "hash": "f543c38b288938e453cf63981d6ce7d5a9f37ddc1eee693345f976be637fef52"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/geometry2d.js",
      "hash": "187e1815b8eb09563b53668a381657a17f39320d0b302c087ea39553e26cee02"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/index.js",
      "hash": "cb84f6f8d0575bf3ac12e1bbbc13823df53082ad981593e62583f1c03f3ffbaf"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/isolated-group.js",
      "hash": "e647c3600593b3a96385e9c8ec95117a95d37c25fbf7bb89b9069d5f447dca1b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/mask2d.js",
      "hash": "8556de02963059a3df06c26046969e1fc71f33005ed4d1341959946242f4179c"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/rendering2d/mesh2d.js",
      "hash": "eacc5b686cb8f7b54680700949a5836518bf7d88a8594ed1c4f062ff3ac592ef"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/scene-object.js",
      "hash": "60f9821ca0a09f0daa8fef04954699660dfb6cdeebb192faa6c3f117bccb84eb"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/scene-timers.js",
      "hash": "3c7b1364e854d3afd45e3781187b3a713ebc4953e349389e4d76cdfd08691592"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/scene.js",
      "hash": "1baaecbc168d7937ee7955ce78e9e0adf7c8ce5e6dcbfddb384d5efc93151d3b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/serialization.js",
      "hash": "6984733a7238266da1c1b805899158a9d70f6e86a692731f6def636acbc75dde"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/shadow-atlas.js",
      "hash": "ea9ed24abfc940b3b801e6adc4b79cd54199d5c853356c525e638b50b391ae1d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/skinned-mesh.js",
      "hash": "66249f5de0945861f736d068b360081392b1dbaa264d769e1ddac97d87c3adaf"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/sprite.js",
      "hash": "ebf64294e6eed5c1b5f41c1444fdd84848ad8beef1ec8b7232ae9aaf632798b0"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/storage.js",
      "hash": "8e15e000d49c0f2477f4850e408f8556b1e7e5837158606a376b6885812c6709"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/text-graphemes.js",
      "hash": "c11669d1affd4732e396b10dc165753f4f8d4e88e272ce65b2a1ca93ec1339cd"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/text-layout.js",
      "hash": "0153e1078a5fc46f2d5ab2d60dd88cafe2630ec45b8dcc884775094a4cbced38"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/text2d.js",
      "hash": "4359d7a4327beae7c6ffa394fec339288ccce0b56b5d315ece1a362a4961d375"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/transitions2d/index.js",
      "hash": "dcdd7fbea6ffb6513b3e9e542938fec6864f985b07ce058ba0cca1a1b1acd369"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/tween.js",
      "hash": "8f82b47687f892288ead789cfd99d24ab8187859046f7028b164a7375e0a3504"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/ui-layout.js",
      "hash": "8bc670332def4afd284b4e9c45bc30e72ab0bfed8ddd1af07c6d985b3f698c55"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/ui-scroll.js",
      "hash": "984d7a160322ed8ecfeed7856147dbc558fd681da7d47dea730babf840416b30"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/ui-text-input.js",
      "hash": "08298e5ff0e6fd2623b1ae76fcce5f84906deb451b84132572b62070733e4c5d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/ui.js",
      "hash": "6a7c47f8efb51162028f7ef6bd6fc3be48fdbadc6e49a65b093c5d2d4f80e019"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/workers/geometry.worker.js",
      "hash": "5fb9f0138f90c75742955f905f87ef05b741661730b63a9c752c71b608837e6d"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/world-streaming-navigation.js",
      "hash": "56f27a8632158029d183b450620090124351177ffa3946ac57b22bd13241778b"
    },
    {
      "path": "vendor/xyz/dist/packages/core/src/world-streaming.js",
      "hash": "95a6db161489d6c93db4ccaa2966a333a86e56341a6cc161cf8ed84aed37b77c"
    },
    {
      "path": "vendor/xyz/dist/packages/ecs/src/index.js",
      "hash": "0e8e0f726b3bf6036f32c3a3cef3cc9d899180d21013739d292209f38488e9bd"
    },
    {
      "path": "vendor/xyz/dist/packages/ecs/src/world.js",
      "hash": "e4b46d5dda8ee7e5e5befd8ca6c57eabe89d29a8ea94b37e9a6e2ca5efbc144d"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/canvas-render2d-targets.js",
      "hash": "1c127010510f026b1c44465b510e5c564f8970af8c519422266ca70069a2cfd3"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/canvas-render2d.js",
      "hash": "e5bcb786f23f7464bc5fe6bb86a2a15950d28b9733dbec88970137ea2ab95024"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/canvas-sprite-source.js",
      "hash": "010e127812bea7f9c26bdec0407176952296c4a2852d83628f6249a2a8ab46cc"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/canvas2d-renderer.js",
      "hash": "4a3d1104bebe44748d180f0a81ca10221de4806b8dfaba0d81238ac5328267b9"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/depth-post-shaders.js",
      "hash": "443089fb502729840cf6b5f0ef38077dd1320a7f77634889588035040f732b78"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/errors.js",
      "hash": "b9fc7607b9141b26dd6f721cb7776b25da2ef15bf24ca87bc4e015c057344f8b"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/fxaa-shaders.js",
      "hash": "581072b0c8a19535b5b5e0a2354746737667ce3fe24dd8dd48c63506e83b74f3"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/gpu-particles3d-data.js",
      "hash": "de90bc858805d93a34a2a2de99885979f519713d4fb80a600c64d645ea7fff95"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/gpu-particles3d-shaders.js",
      "hash": "0c61065c42d7f617e4f69ef396e17976c2e801ed7e18da823aa63746f578741f"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/gpu-timing.js",
      "hash": "db5c40ffb89e5ae5774c9b8d1acf87d0dbaa5519f6883765d88c93219512757f"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/index.js",
      "hash": "857d0ba24bcdf313ccadb65e013fb53092765222571c14102fedfaca81fd9328"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/material-uv.js",
      "hash": "e4b4d139260c707bedf1acbdceeb126218310914321e5bb4bf77ba6a057b348e"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/native-material-limits.js",
      "hash": "ac04ea37a219f641ad9862bb8fa60f12924fd742002e2e42c53ce4b24f27215f"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/native-texture-upload.js",
      "hash": "94cd7554c60c6f208582132a6d1949477b1a83d43d99f781c329304643163383"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/occlusion-proxy.js",
      "hash": "91d532804d77300eb81e361ccff97e2d98a237b6cfce4c4ff6a091b942b622d1"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/oit-shaders.js",
      "hash": "653e0714efedcc8321d127dd1a75a3c443f83643aa40db08e43f0b990aef0027"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/optical-maps.js",
      "hash": "ee02c511f3b27c325e59dfc062a3ee3f578d9e3a3ee6a336e61d2b2633483959"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/optical-pack-shaders.js",
      "hash": "373b0340f56d6d9172bc8b9999dd25a8f7c0b4a9135c93f77368d8beb528987e"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/preparation.js",
      "hash": "7485a142cea7dd8cc0def766defbfbea0cd8fcc6d7ddb0b3f6d0db835f3739e7"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/presented-renderer.js",
      "hash": "b7d8e5fd884c1ed02059079fa43f1b6d2479a63821612d2f7d9bba03426eaef1"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/reflection-probe-shaders.js",
      "hash": "f4aaef7c200f85226b928916fe258a0cf10566791ef2b2c6f76b29cab6b4217c"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/render-stats.js",
      "hash": "d9fb7af78ab3f7c51b375c05909c2a515bf8c297a01780ea87c13644d2f1814b"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/render-texture2d.js",
      "hash": "6cfdb04964dd7b4aedfbf9b1b3e625af365d6b7b33acdbe73a232943065815d5"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/render2d-contract.js",
      "hash": "b7dff4bdf0a387d4f76eed2c671aa862ec5eb181d340696c0c9184b4b6627297"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/residency.js",
      "hash": "d0c8b10bb7ef588ea0835cb25084327df518c914de7ad923caeb92105e9c26fc"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/resilient-renderer.js",
      "hash": "6755439cab905d436246ab2319ed1e6798da5f4b0f886bfcfbafb6ff68789eba"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/shadow-cache.js",
      "hash": "a60f0e176696cf0b0a13c8e434263120512d4f6a9fd2560a327234bb18054d1f"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/shadow-shaders.js",
      "hash": "ea453adb1b7da1807134eef68de64fce79f549020d7042ae310e05e324362493"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/sheen-shaders.js",
      "hash": "96db0d0b841ef37e6f5b23175bd7a5b544cce9d868b5e80bea17c8785ef6e8fb"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/sprite-instance.js",
      "hash": "8ec73bb572ddc62a2903e3ce5e31630ee0312dd4d079905c31bee9fd46a8f680"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/transmission-shaders.js",
      "hash": "e9a1a45b5983b6fb6dfe16679e6982e0bf796ea3b6925102d41e605ff079fd62"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/warmup.js",
      "hash": "e581586153e88dd8f09c8343c2f1237f05bccdf4abd6731c0f905eaafeeafab5"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl-2d/shaders.js",
      "hash": "14c91d33fce4d514c9f70bbce894d27453d5105eec3234b785c49b14dd31cf03"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl-feature-shaders.js",
      "hash": "67bce0cc2906b4ee48c5a10de9c3cbbea4b71404d6d97ac727bf44d80d2628f4"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl-occlusion.js",
      "hash": "4a6a68bf9a479c2230382e978714a5de08a4038bef53c3fdd67062c7f17db7d6"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl2-particles3d.js",
      "hash": "bb0aef77ad064922425c7f3198d157440832166966583aaa226a3bc5b0278353"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl2-render2d-shaders.js",
      "hash": "bf0d9775ac7d2ca7647a8132fe761c2a9dc45749cc234ed4bac5151bc12dda2d"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl2-render2d.js",
      "hash": "f0c8cb4277d55510dfd77d3d11a05eb96ad3fd5ff212361e96de0007503e5033"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgl2-renderer.js",
      "hash": "7cb780215bc9527ef88857d59e3f7674dc234a0edaed2f52c05b9eed3824e86a"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-2d/effects.js",
      "hash": "52731a06e0d805ad2208722e8d08e6107ae1ec4e27d5269286c180b0b46ed8ff"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-2d/shaders.js",
      "hash": "ae1aeffbe76e858fac99ef38d148f2815314bbd29210c157a09fab50432dccae"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-mesh-pipeline.js",
      "hash": "b44d2eb015604c1a7803ae9b31b83f20c7ac2b26fb4618885e58fefd1ea48001"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-mesh-shader.js",
      "hash": "d9cbfcdd6f656cee141a0c536e6a5b1387ce8f9af08f562387ca70c035436df0"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-occlusion.js",
      "hash": "419af60cd2f6f00a5074cf0902801365235057d9a11ff0cf69f1f2a2a72f0877"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-oit.js",
      "hash": "6b73f592a0bc2eb1a730cdc5540cce8a1e591fc18f802b27a79075c5e5786e6d"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-particles3d.js",
      "hash": "a0daff19ed03fae0f0b0847bcd2feee3abf094565175efd9b421c2c2c669a94e"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-post-pipeline.js",
      "hash": "8e91715ef797edc98e415eb353f66fc4d227c7b1a4f305bc98838f4bc6d956e8"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-render2d-shaders.js",
      "hash": "8aa3a6cf614c71f5ade8e709bf9a8d46c5b57d92272b2829c1035b66d9f618c7"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-render2d.js",
      "hash": "3b8545e3573f33e6da61a25670280e8e69528326a45befac1e93cb5313c7758f"
    },
    {
      "path": "vendor/xyz/dist/packages/graphics/src/webgpu-renderer.js",
      "hash": "6c8d29b44a048117f0d4a63ac8e232a7030a3908cee13ac5050fb88a261c987a"
    },
    {
      "path": "vendor/xyz/dist/packages/input/src/contexts.js",
      "hash": "41d83647afe77e8a62ea3d843c479cebadbd3a5f84a5d7a72fe7468e42a994e7"
    },
    {
      "path": "vendor/xyz/dist/packages/input/src/gamepad.js",
      "hash": "4c4f46c0dde66bac9d3fa7c2c9686b5e0e22ded76d52473f77e961588ddb33b6"
    },
    {
      "path": "vendor/xyz/dist/packages/input/src/gestures.js",
      "hash": "849f598ae78b3a0469df4dbfab01612dccef229de96128871dac7d64baf57f38"
    },
    {
      "path": "vendor/xyz/dist/packages/input/src/index.js",
      "hash": "b1865c6dfded5f4343ecf1f32b73714072c0c24ca977862109cfe37b616735d0"
    },
    {
      "path": "vendor/xyz/dist/packages/input/src/virtual.js",
      "hash": "4058d515dd156101c8eb57610108ef3119ccb14bf0569da16c7272e9c80664ec"
    },
    {
      "path": "vendor/xyz/dist/packages/math/src/index.js",
      "hash": "c6ff9206c727537499704b96106f8e254bcf2763878cd2227df936a989b0f686"
    },
    {
      "path": "vendor/xyz/dist/packages/math/src/math3d.js",
      "hash": "31a0c61aca355e34e5759524d5378e1ef5df539d608dddccb3101f872cb7cb61"
    },
    {
      "path": "vendor/xyz/dist/src/data/accessibility.js",
      "hash": "43fcce9aecd1248da831b06662c7e0a886bddc87a77e5ca1ca68f9888b3ca00a"
    },
    {
      "path": "vendor/xyz/dist/src/data/actions2d.js",
      "hash": "f552e83b9bd7b354a2b665b8419b2f2df04e9a402e1764dabaab0614c0abab2e"
    },
    {
      "path": "vendor/xyz/dist/src/data/asset-recipe.js",
      "hash": "bb0677a9afb5428f022dba483f40240f4ffbce90e96ab711c6088379b56f8bc8"
    },
    {
      "path": "vendor/xyz/dist/src/data/assets.js",
      "hash": "1ea2c1429433cc80b5fd05e436c52e35e146fff34fd43e023376992d64d9916f"
    },
    {
      "path": "vendor/xyz/dist/src/data/audio.js",
      "hash": "218e63b733284ce167e0cf2314414e7fe9165dc3f954d708fe8ecc8944e17ecc"
    },
    {
      "path": "vendor/xyz/dist/src/data/beacon-run.js",
      "hash": "afcf659430623a185069687aa56e69165efd2f354ed0a8e8a7bbca2b805cb601"
    },
    {
      "path": "vendor/xyz/dist/src/data/character3d.js",
      "hash": "ab28fb7ad6cb8835445aeb525c40e2a90dbce0232bbf037c98c7fe0c122f86ac"
    },
    {
      "path": "vendor/xyz/dist/src/data/content.js",
      "hash": "529ed545f24ceb004d5e3b1b266ba028ec734a339317293804db9196de9bcd77"
    },
    {
      "path": "vendor/xyz/dist/src/data/defaults.js",
      "hash": "5813bedd48ffb5bc74fc64ce14e411ae3bc2b8d9d0d256c19cc8e6e289ed57e7"
    },
    {
      "path": "vendor/xyz/dist/src/data/gameplay-assets.js",
      "hash": "69b448d0cf34dd074261006828e10b415b7f9e557d1047a2fbd6f108bd367d35"
    },
    {
      "path": "vendor/xyz/dist/src/data/gpu-particles3d.js",
      "hash": "642b87eb212427b806485f5e384d21dce0e9b5c0aa9fef7b20d1ef607b68d285"
    },
    {
      "path": "vendor/xyz/dist/src/data/graphics2d.js",
      "hash": "c4885b3e382ef500e724ae98636001a7825a67ec6523be0ef336a97420848aba"
    },
    {
      "path": "vendor/xyz/dist/src/data/input.js",
      "hash": "acbe6a7de7a98f1a57a451555fa6ec65766cd3591a8774cd122541f05f42d633"
    },
    {
      "path": "vendor/xyz/dist/src/data/lights.js",
      "hash": "93b61a2969a27f6ec666aaa411b4a88a224efc14cedf402f00916aa1cf30b6e5"
    },
    {
      "path": "vendor/xyz/dist/src/data/locomotion3d.js",
      "hash": "cdf5f1a72d9cb7cf9112371041706d022f687edca13bcf67924c0f03e194c877"
    },
    {
      "path": "vendor/xyz/dist/src/data/materials.js",
      "hash": "0c541d6a6887145c91a49a2abc1836b291c4f9a4111e34ae3b0a49ec28d454da"
    },
    {
      "path": "vendor/xyz/dist/src/data/materials2d.js",
      "hash": "0617a1733bdddaf27f9e38c46a6f8bc839cac65ce50d9a1a6b99bde62e6b18bc"
    },
    {
      "path": "vendor/xyz/dist/src/data/models.js",
      "hash": "fd4ab77e3a9a7aac50594bde0b7a12af648b759f2308f3aba94395e41fe31cc4"
    },
    {
      "path": "vendor/xyz/dist/src/data/navigation.js",
      "hash": "30c51df9546956532be111b0ec5e6f353987c82b0f0649823566dcf1d453d0ed"
    },
    {
      "path": "vendor/xyz/dist/src/data/observability.js",
      "hash": "3871f2b29849aa8ea8f43fd867d5733759ba8db0f1f3073a4ea77d1840044d59"
    },
    {
      "path": "vendor/xyz/dist/src/data/physics-ray.js",
      "hash": "bbaf35b6af8705ee5afb486e70027fe508626e78a54bc085834092650de244a2"
    },
    {
      "path": "vendor/xyz/dist/src/data/physics3d.js",
      "hash": "160cba0a6f1a8e592f9a8ee0363c7100ec3b601b830a6c2f9fd8a7365faaeb54"
    },
    {
      "path": "vendor/xyz/dist/src/data/rendering.js",
      "hash": "158551a2fdeca60bfcec24cbdee8c6cd62349c9b964d33a1bd3e9e8c5f486c78"
    },
    {
      "path": "vendor/xyz/dist/src/data/rendering2d.js",
      "hash": "b1474faa8cab0a6f1e298230b3f53c39c3e54433b0a3699bd9942919024ec3e9"
    },
    {
      "path": "vendor/xyz/dist/src/data/sheen.js",
      "hash": "d3799f81ef77046fd9c1e5a0d39455c82767daa62102f293cd1f290dcadef4b4"
    },
    {
      "path": "vendor/xyz/dist/src/data/simulation.js",
      "hash": "5ad7fee7e14395eee303fa9cd95725d0a7df3b8749200ddb0de1f8abf5951297"
    },
    {
      "path": "vendor/xyz/dist/src/data/startup.js",
      "hash": "42ba73482201343a3417716d1ae44f26c4f355bb5ce14bc234bc4d1ec90da72b"
    },
    {
      "path": "vendor/xyz/dist/src/data/storage.js",
      "hash": "e056ee75f4341aaa7a51fa8d1a2fbb5965af598e5f06b4530354fe5a32d860a2"
    },
    {
      "path": "vendor/xyz/dist/src/data/text.js",
      "hash": "997600487a075c1edc21ca35dc6aa35ce9b33ca369a9547ff811644b5e63c023"
    },
    {
      "path": "vendor/xyz/dist/src/data/tiled.js",
      "hash": "5b92601bf309025fbbf55be7199e25ca9160fd92a77ce0a7aebf743494042f97"
    },
    {
      "path": "vendor/xyz/dist/src/data/ui.js",
      "hash": "b5d0f289c1e793d8635bc02917fa25623b566ee0cbd72c8b4362fdd496a692b0"
    },
    {
      "path": "vendor/xyz/dist/src/data/visibility.js",
      "hash": "3b4590d64692f402871f549c6a841d35f9c2d7addb0af5ce4cee5ce465989ee9"
    },
    {
      "path": "vendor/xyz/dist/src/data/worker-jobs.js",
      "hash": "c1c3e6439e4cc378e90faab4f9370bced5f6f82f1332e2fa8ccb9d97dd53a766"
    },
    {
      "path": "vendor/xyz/dist/src/data/world-streaming.js",
      "hash": "dc4d57eef577183cf8f4f5dafe09ce8ff2c889a4d3c3033712160c77c00350c4"
    },
    {
      "path": "vendor/xyz/dist/src/data/world2d.js",
      "hash": "29fd49ed6154000d2444385fd54d48db2b5408a10bbab366c3b07d90f327aa70"
    },
    {
      "path": "vendor/xyz/dist/src/index.js",
      "hash": "97723de5ce49a3ce76226609f93b3fcb08b5f7e3e4544ed2a8be9f5cb446b615"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/arrangement.js",
      "hash": "9799b746578001ad36f67c5108da6c716c632e823f7e6f12bfdd72cb0e2768cf"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/fx.js",
      "hash": "b43269fc09ea73639aef2529a73236ec2baba84de0830d8b8a417038b3ae284b"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/index.js",
      "hash": "ad1f10188a1448f5a2513255a3bf5c6b10f20761e7d6998a26ed8916c4ace8f1"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/midi.js",
      "hash": "e0cc24220cdee0eb0be316c8d99ce96d474151a13d7996ccacd6d38294a0001e"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/performance.js",
      "hash": "297bc80f32fbb4409f78d1b44eee03b0b272bc0478f73500c878b3f2235cf291"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/render-worker.js",
      "hash": "2a93999bd2e174b326bf3d320b197cfb44ab95b9265ffb1d8275e4c71340397b"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/sequence.js",
      "hash": "a28cc67dba6e91850719c1dba13e51d2fd1e954cc56758734290ce63775f2e09"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/api/transport.js",
      "hash": "e4de16e31637b280df509cf98aada2189760e3f93c79ec2bc964afce9d76ca34"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/algorithms.js",
      "hash": "3375c0f70f25b7c9835fde2c24bb23f8857ceb2b169727766fbd9445d873bf97"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/arrangement-definition.js",
      "hash": "13100b846b84978af2539c59392f09024221259447f9ee13f4c62e7427bff529"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/decimator.js",
      "hash": "79f7e25d1f576d91cb2651c04e40ccd73146c7983e443011aa6bcd0bdffe9707"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/envelope.js",
      "hash": "dcec4fc4cd557d283fdccbd770b4cdd4c6ccd0efcf0976c53006a902c2d502c1"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/fx.js",
      "hash": "4babd07acd9e44167419aabee0ca046668a9e511247f477f5179af606b2173ad"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/index.js",
      "hash": "49216f8de5a75c89e333e4730dbb0d0ebaba2398a7dc57d416099deee1e4f308"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/lfo.js",
      "hash": "fda0aa13373353b9bce90f079b2e16524923870c95251d42597e6e8748888fe2"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/midi-file.js",
      "hash": "d3e80fee02e2ecb8b4ea14323d2ad2dc87e05840287b04af7476bf2fbea5ca15"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/midi-state.js",
      "hash": "b35e52e3bcd542b7bf4482fa2ba894dfbb8507bb057c8297464db96d0fa448ae"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/operator.js",
      "hash": "2edb363f150e84e2e169e1c138f038e52ca5758f7ea95048cfa8021e539ae8f1"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/project.js",
      "hash": "67e478f5ced2fb6abe658da389e5cf83868417d4e884b9722fd6a8ca4c173ad8"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/sequence.js",
      "hash": "d514dde06f65ce8e9ae9cc832f7e3c0cf687e49162bac2948515f2468991f085"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/synth.js",
      "hash": "f37fd191393a97c5e56fc4862633f28291808c50a403f337e8139275f42d5b86"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/transport.js",
      "hash": "4422cc5ad6eb805fd8f30964227ede1502c0cd47dcfbc7944c9fbc107d167f01"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/tuning.js",
      "hash": "ee763f199cfb63f5ad411db3d6bb680456a400e4d89e7ca6e03347c185339f4c"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/core/wav.js",
      "hash": "69c73c90bf56e0b6c1c787858577854a491d0d249f0410f28c96d445537a7900"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/adaptive.js",
      "hash": "505469ca42947567107007dda5d244e553301426f10b57b94133434fadcc362d"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/audition.js",
      "hash": "d204883cc18daf8b2968bc4cf68e0f3489fdf5e3ec9a8a61e74c04c7a3ca0b94"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/basic.js",
      "hash": "7eeff77bb0adbd0250454e1b3d1bef31ffac2ede67b62b2b43854fd99f172577"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/buses.js",
      "hash": "152f53d1ea6db46dc5815e37b2f51ff313d2dd1179de8efbc215fd96ea005720"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/context.js",
      "hash": "6142db87b95694dd5f23e271840de348c4e0dc166e3d1377f9afa6aeaed636f1"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/instrument.js",
      "hash": "4e3e13ec80a98f574b37c62847f10ab35d1ca8606c33a12b3ef29fe3938c282f"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/main.js",
      "hash": "3bddf2c5061423188ef53944a63ab4a99e503a0767b2417be30d9b822000ad25"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/modulation.js",
      "hash": "2ed7c4b804bf3d92f39b87644a9d43b03ffadd1a9df695e4820d7dda38076f6d"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/sequence.js",
      "hash": "9c1cc524046a0b82635bc0dae7d3c0992973aac8b64d3231886ecd2852d2d4e2"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/showcase.js",
      "hash": "a2aadc271b1de15ffccbbed10f81a7133bdca50f89e6d1e8e489a73547cf4090"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/song.js",
      "hash": "a8cbca915595f93501943e07c1d32f49041bba9abcb4604a91e663b930a1f178"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/sound-design.js",
      "hash": "23fecfa8808e2a5a0a19b593e9975cb5a74b55a5a491c7dcdb52ad0e25684cca"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/demo/wav.js",
      "hash": "b003921534b3cd5c4f90a2ebbda941328fbf3c8ab5177b50facf80413c825127"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/version.js",
      "hash": "36ea51a9aad23fad8ecfb506ee080b13916aec36f9b27964182de6203f63c7c6"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/brass.js",
      "hash": "4214e578e0973e8effd7c674ddd2b1d28ab78c1e6ddb817563c9ce5408c9a1eb"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/dx7.js",
      "hash": "82011520ef8c210df82885dc1de042e0038797e83cbf9ab70a8c5900506185c2"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/examples.js",
      "hash": "ed0c5fd7501a5314980314f0eb7a1fffd185c3edfbe79fb7ba5ad407c44f9c2b"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/gm-map.js",
      "hash": "c64a2456ea766bb67b1152cc2b474440044d86f69854d866fc37d8dfe7ddf9bc"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/normalize.js",
      "hash": "efc9fb969137385d5f344196efaa38b28132eeda91e0415cdebd6f2a5d661d72"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/opm.js",
      "hash": "50f7e73e29d989841d33b1935b5df6b9381c6953bce778880ef413296ad70007"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/original.js",
      "hash": "0ae75903284ff7f6ff63847e545c60685025e1c772eccab4d48f138fc6106f67"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/preset-metadata.js",
      "hash": "415c869867b0bafc22dd5a6fcb4d9cdbd3ad04993438446d727989f8e3577c19"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/schema.js",
      "hash": "1b4742de7234321699255be6baca8ef77086b52fafc9b5f8f244887431d1f88b"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/voices/voice.schema.js",
      "hash": "40a6736d88e296f85601c49ef1beaa82300ef535ac1c02697928b2ab66bad027"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/worker/render.js",
      "hash": "ce320a5d618702fcc4427f88f499e6a55dba47db76ad078e4801505e632cfc9a"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/worklet/fx-processor.js",
      "hash": "4c06cfe00c6c6d6833a4d595a107769b0f80418446fed5f3390a92e50bc07086"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/worklet/processor.js",
      "hash": "879c7971ee6e0204f5aff301caf2833015a4b93bfa48caa0850b798e4c0c3ab0"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/dist/worklet/worklet-globals.js",
      "hash": "1cfea04718e3397d6304e79e9a96587b27b9904b53f8ca88679c50ecd5210e99"
    },
    {
      "path": "vendor/xyz/dist/vendor/opm/manifest.json",
      "hash": "9d5031d5fc2311830fc5482c9cf478447f2f96b13edc7030027bce9ac3340743"
    }
  ]
};
