const rows = {
  title: ['圖鑑', 'Codex', '図鑑'], mages: ['法師', 'Mages', '魔法使い'], spells: ['法術', 'Spells', '魔法'], enemies: ['敵人', 'Enemies', '敵'], bosses: ['首領', 'Bosses', 'ボス'], reactions: ['反應', 'Reactions', '反応'],
  collection: ['純收藏，不提供能力加成', 'A collection, not a source of power', '収集のみ。能力への補正はありません'], download: ['下載收藏卡', 'Download card', 'カードを保存'], exporting: ['正在繪製…', 'Rendering…', '描画中…'], failed: ['無法匯出收藏卡，請再試一次。', 'Could not export the card. Please try again.', 'カードを保存できませんでした。もう一度お試しください。'],
  unknown: ['尚未發現', 'Not yet discovered', '未発見'], hint: ['在旅途中遇見，即可收錄。', 'Encounter this entry on a run to discover it.', '冒険中に出会うと図鑑に登録されます。'], mageHint: ['使用這位法師出征。', 'Begin a run with this mage.', 'この魔法使いで冒険を始めよう。'], spellHint: ['在升級時選取此法術；進化配方始終公開。', 'Choose this spell on level-up. Evolution recipes are always public.', 'レベルアップで選ぼう。進化レシピはいつでも公開。'],
  recipe: ['進化配方', 'Evolution recipe', '進化レシピ'], seen: ['已發現所需法術', 'Required spell discovered', '必要な魔法を発見済み'], unseen: ['先取得所需法術', 'Discover the required spell first', 'まず必要な魔法を見つけよう'], evolved: ['已完成此進化', 'Evolution achieved', '進化達成済み'], passiveGuide: ['被動道具可於升級選取；需在同一局達到所示等級。', 'Pick the item on level-up; reach both required levels in the same run.', 'レベルアップでアイテムを選び、同じ冒険で両方の必要レベルに到達しよう。'],
  passive: ['天賦', 'Innate passive', '固有能力'], start: ['起始法術', 'Starting spell', '初期魔法'], family: ['族群', 'Family', '種族'], hp: ['生命', 'HP', 'HP'], xp: ['經驗', 'XP', '経験値'], maps: ['出現地圖', 'Found in', '出現マップ'], from: ['首次出現（基準難度）', 'First arrival (base difficulty)', '初出現（基準難易度）'], child: ['由母體分裂產生', 'Appears when its parent splits', '親が分裂すると出現'], patterns: ['招式', 'Patterns', '技'], tiers: ['首領生命：8 / 14 / 18 分鐘', 'Boss HP: 8 / 14 / 18 minutes', 'ボスHP：8 / 14 / 18分'],
  swarm: ['散兵：成群追擊，保持移動。', 'Swarm: pursues in packs. Keep moving.', '群れ：集団で追跡する。動き続けよう。'], fast: ['快怪：突然撲擊，留出閃避空間。', 'Hunters: lunges suddenly. Leave room to dodge.', '俊足：不意に飛びかかる。回避の余地を残そう。'], tank: ['肉盾：緩慢而堅韌，不易擊退。', 'Tanks: slow, durable and hard to knock back.', '重装：遅く頑丈で、押し戻しにくい。'], ranged: ['射手：保持距離，以彈幕封路。', 'Ranged: keeps its distance and blocks routes with shots.', '遠距離：距離を保ち、弾幕で道を塞ぐ。'], split: ['分裂：擊殺後仍需提防子體。', 'Splitters: beware the offspring after a kill.', '分裂：倒した後も子に注意。'], exploder: ['自爆：靠近後點燃引信，迅速遠離。', 'Exploders: lights a fuse up close. Retreat quickly.', '自爆：近づくと起爆する。素早く離れよう。'], flyer: ['飛行：無視地形直撲目標。', 'Flyers: crosses terrain to reach you.', '飛行：地形を越えて襲いかかる。'], buffer: ['增益：強化附近盟友，優先清除。', 'Buffers: empowers nearby allies. Prioritize it.', '強化：周囲の味方を強める。優先して倒そう。'], healer: ['治療：回復附近敵人，切斷支援。', 'Healers: restores nearby foes. Cut off their support.', '回復：周囲の敵を治療する。支援を断とう。'], summoner: ['召喚：持續呼叫援軍，避免敵群膨脹。', 'Summoners: calls reinforcements. Stop the horde from growing.', '召喚：増援を呼び続ける。群れが増える前に倒そう。'],
  arcane_rings: ['奧術環', 'Arcane rings', '秘術の環'], rune_seals: ['符文封印', 'Rune seals', 'ルーン封印'], summon_constructs: ['召喚構裝體', 'Summon constructs', '構造体召喚'], barrage_spiral: ['螺旋彈幕', 'Spiral barrage', '螺旋弾幕'], root_eruption: ['根鬚突刺', 'Root eruption', '根の噴出'], spore_cloud: ['孢子雲', 'Spore cloud', '胞子雲'], seed_barrage: ['種子彈幕', 'Seed barrage', '種子弾幕'], treant_call: ['樹人呼喚', 'Treant call', '樹人の呼び声'], frost_breath: ['冰霜吐息', 'Frost breath', '氷の息吹'], icicle_rain: ['冰柱雨', 'Icicle rain', '氷柱の雨'], blizzard_dash: ['暴雪突進', 'Blizzard dash', '吹雪の突進'], ice_golems: ['冰魔像', 'Ice golems', '氷のゴーレム'], ground_slam: ['撼地重擊', 'Ground slam', '地砕き'], lava_pools: ['熔岩池', 'Lava pools', '溶岩池'], fire_ring_volley: ['火環齊射', 'Fire-ring volley', '火輪斉射'], magma_bombers: ['熔岩爆破兵', 'Magma bombers', '溶岩爆撃兵'], gravity_wells: ['重力井', 'Gravity wells', '重力の井戸'], gaze_sweep: ['凝視掃射', 'Sweeping gaze', '薙ぎ払う視線'], rift_summons: ['裂隙召喚', 'Rift summons', '裂け目召喚'], void_spiral: ['虛空螺旋', 'Void spiral', '虚空の螺旋'],
};
export default Object.fromEntries(['zh', 'en', 'ja'].map((lang, i) => [lang, Object.fromEntries(Object.entries(rows).map(([key, value]) => [`codex.${key}`, value[i]]))]));
