export default {
  en: {
    'save.transfer': 'Keep your progress safe', 'save.localHint': 'Progress lives on this device. Export a copy before changing browsers.', 'save.download': 'Export JSON file', 'save.copy': 'Copy save code', 'save.import': 'Import a save', 'save.code': 'Save code', 'save.paste': 'Paste a save code or JSON here…', 'save.pickFile': 'Choose JSON file', 'save.preview': 'Preview import', 'save.backup': 'Previous save', 'save.restore': 'Restore previous save', 'save.noBackup': 'No backup yet. One is created when you import a save.', 'save.backupSummary': '{runs} runs · Best score {score}',
    'save.version': 'Save version', 'save.mages': 'Unlocked mages', 'save.spells': 'Unlocked spells', 'save.maps': 'Unlocked maps', 'save.maxDifficulty': 'Max difficulty', 'save.bestScore': 'Best score', 'save.runs': 'Runs played', 'save.createdAt': 'Created',
    'save.overwriteWarning': 'This replaces your current progress and settings. Your current save will be backed up first.', 'save.restoreWarning': 'Replace current progress and settings with this backup?', 'save.imported': 'Save imported. Your previous save was backed up.', 'save.restored': 'Previous save restored.', 'save.failed': 'Could not update the save. Your current save is unchanged.', 'save.invalid': 'Invalid or unsupported save. Check the code or choose a valid Hexsurge JSON file. Nothing was changed.', 'save.empty': 'Paste a save code or choose a JSON file first.', 'save.tooLarge': 'This file or code is too large (maximum 2 MB). Nothing was changed.', 'save.readFailed': 'Could not read this file. Please choose it again.', 'save.copied': 'Save code copied.', 'save.copyManual': 'Clipboard unavailable. The code is selected below; copy it manually.', 'save.downloaded': 'JSON download requested.', 'save.loadFailed': 'Your old save could not be loaded. It has been preserved; export or restore a valid save.',
  },
  zh: {
    'save.transfer': '守護你的進度', 'save.localHint': '進度儲存在此裝置；更換瀏覽器前，請先匯出備份。', 'save.download': '匯出 JSON 檔案', 'save.copy': '複製存檔碼', 'save.import': '匯入存檔', 'save.code': '存檔碼', 'save.paste': '在此貼上存檔碼或 JSON…', 'save.pickFile': '選擇 JSON 檔案', 'save.preview': '預覽匯入', 'save.backup': '前一份存檔', 'save.restore': '還原前一份存檔', 'save.noBackup': '尚無備份；匯入存檔時會自動建立。', 'save.backupSummary': '遊玩 {runs} 局 · 最高分 {score}',
    'save.version': '存檔版本', 'save.mages': '已解鎖法師', 'save.spells': '已解鎖法術', 'save.maps': '已解鎖地圖', 'save.maxDifficulty': '最高難度', 'save.bestScore': '最高分', 'save.runs': '遊玩局數', 'save.createdAt': '建立日期',
    'save.overwriteWarning': '這會取代目前的進度與設定；覆蓋前將自動備份目前存檔。', 'save.restoreWarning': '確定以此備份取代目前的進度與設定？', 'save.imported': '已匯入存檔；原存檔已備份。', 'save.restored': '已還原前一份存檔。', 'save.failed': '無法更新存檔；目前存檔未變更。', 'save.invalid': '存檔無效或版本不支援。請檢查存檔碼，或選擇有效的 Hexsurge JSON 檔案；目前存檔未變更。', 'save.empty': '請先貼上存檔碼或選擇 JSON 檔案。', 'save.tooLarge': '檔案或存檔碼過大（上限 2 MB）；目前存檔未變更。', 'save.readFailed': '無法讀取檔案，請重新選取。', 'save.copied': '已複製存檔碼。', 'save.copyManual': '無法使用剪貼簿；下方已選取存檔碼，請手動複製。', 'save.downloaded': '已開始下載 JSON。', 'save.loadFailed': '舊存檔無法載入，但已保留；請匯入或還原有效的存檔。',
  },
  ja: {
    'save.transfer': '進行状況を守ろう', 'save.localHint': '進行状況はこの端末に保存されます。ブラウザーを変える前に書き出しましょう。', 'save.download': 'JSON を書き出す', 'save.copy': 'セーブコードをコピー', 'save.import': 'セーブを読み込む', 'save.code': 'セーブコード', 'save.paste': 'セーブコードまたは JSON を貼り付け…', 'save.pickFile': 'JSON ファイルを選ぶ', 'save.preview': '読み込み内容を確認', 'save.backup': '以前のセーブ', 'save.restore': '以前のセーブを復元', 'save.noBackup': 'バックアップはまだありません。読み込み時に自動作成されます。', 'save.backupSummary': '{runs} 回プレイ · 最高スコア {score}',
    'save.version': 'セーブのバージョン', 'save.mages': '解放済みの魔法使い', 'save.spells': '解放済みの魔法', 'save.maps': '解放済みのマップ', 'save.maxDifficulty': '最高難易度', 'save.bestScore': '最高スコア', 'save.runs': 'プレイ回数', 'save.createdAt': '作成日',
    'save.overwriteWarning': '現在の進行状況と設定を置き換えます。上書き前に現在のセーブを自動でバックアップします。', 'save.restoreWarning': '現在の進行状況と設定をこのバックアップで置き換えますか？', 'save.imported': '読み込み完了。以前のセーブをバックアップしました。', 'save.restored': '以前のセーブを復元しました。', 'save.failed': '更新できませんでした。現在のセーブは変更されていません。', 'save.invalid': '無効、または未対応のセーブです。コードを確認するか、有効な Hexsurge JSON を選んでください。変更はありません。', 'save.empty': 'コードを貼り付けるか、JSON ファイルを選んでください。', 'save.tooLarge': 'ファイルまたはコードが大きすぎます（上限 2 MB）。変更はありません。', 'save.readFailed': 'ファイルを読めませんでした。もう一度選んでください。', 'save.copied': 'セーブコードをコピーしました。', 'save.copyManual': 'クリップボードを使えません。下のコードを選択しました。手動でコピーしてください。', 'save.downloaded': 'JSON のダウンロードを開始しました。', 'save.loadFailed': '以前のセーブを読み込めませんでした。元データは保持されています。有効なセーブを読み込むか復元してください。',
  },
};
