import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { dirname, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

// Release maintenance only; the game runs directly from checked-in modules.
// Browser audio unlock loads vendor/opm/dist/api/index.js and the OPM module graph.
// Its worklet/processor.js, fx-processor.js and worker/render.js are runtime URLs,
// not static imports from app.js. Include all runtime JS plus JSON/WASM payloads.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
async function walk(directory) {
  const files = [];
  for (const entry of await readdir(resolve(root, directory), { withFileTypes: true })) {
    if (['tools', 'tests', 'docs'].includes(entry.name)) continue;
    const path = posix.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(path));
    else if (!/\.map$|\.d\.ts$/.test(path) && entry.name !== 'debug.js'
      && (!directory.startsWith('vendor/') || /\.(js|json|wasm)$/.test(path))) files.push(path);
  }
  return files;
}
const paths = ['index.html', 'app.js', 'manifest.webmanifest', 'favicon.ico',
  ...await walk('assets'), ...await walk('src'), ...await walk('vendor/xyz/dist')].sort();
const assets = await Promise.all(paths.map(async path => ({ path, hash: digest(await readFile(resolve(root, path))) })));
const version = digest(assets.map(({ path, hash }) => `${path}\0${hash}\n`).join(''));
const inventory = `// Generated by tools/build-cache.mjs; regenerate after all release edits.\nself.HEXSURGE_RELEASE = ${JSON.stringify({ version, assets }, null, 2)};\n`;
const target = resolve(root, 'sw-assets.js');
if (await readFile(target, 'utf8').catch(() => '') !== inventory) await writeFile(target, inventory);
console.log(`Precache: ${assets.length} assets; SHA-256 release ${version}`);
